"""Traductions arabes (oct. 2026). Clé : le texte français exact tel
qu'il apparaît dans les modèles ; valeur : sa traduction.

Un texte absent de ces listes s'affiche simplement en français. Pour
traduire un nouvel écran : entourer ses textes de _("…") dans le modèle,
puis les ajouter ici. À faire relire par un arabophone de l'école."""

# --- Interface ----------------------------------------------------------------

INTERFACE = {
    # Menu et barre du haut
    "Ouvrir le menu": "فتح القائمة",
    "Tableau de bord": "لوحة القيادة",
    "Plateforme": "المنصة",
    "Fiche": "البطاقة",
    "Scolarité": "التمدرس",
    "Bulletin": "كشف الدرجات",
    "Mon espace": "فضائي",
    "Ma fiche": "بطاقتي",
    "Mon bulletin": "كشف درجاتي",
    "Mon emploi du temps": "جدول حصصي",
    "Classes": "الأقسام",
    "Élèves": "التلاميذ",
    "Tests de niveau": "اختبارات المستوى",
    "Documents officiels": "الوثائق الرسمية",
    "Pédagogie": "الشؤون التربوية",
    "Notes et bulletins": "الدرجات والكشوف",
    "Absences": "الغيابات",
    "Emplois du temps": "جداول الحصص",
    "Enseignants": "المدرسون",
    "Mes classes": "أقسامي",
    "Suivi des cours": "متابعة الدروس",
    "Alertes": "التنبيهات",
    "Finances": "المالية",
    "Caisse": "الصندوق",
    "Salaires": "الرواتب",
    "Statistiques": "الإحصائيات",
    "Messages": "الرسائل",
    "Relances WhatsApp": "التذكيرات عبر واتساب",
    "Annonces": "الإعلانات",
    "Bibliothèque": "المكتبة",
    "Assistant": "المساعد",
    "Administration": "الإدارة",
    "Demandes de comptes": "طلبات الحسابات",
    "Comptes et rôles": "الحسابات والأدوار",
    "Établissement": "المؤسسة",
    "Télécharger une sauvegarde": "تنزيل نسخة احتياطية",
    "Mon profil": "ملفي الشخصي",
    "Déconnexion": "تسجيل الخروج",
    "Propulsé par": "بدعم من",
    "Rechercher un nom…": "البحث عن اسم…",
    "Rechercher un élève, un enseignant ou un compte": "البحث عن تلميذ أو مدرس أو حساب",
    "Connexion": "تسجيل الدخول",
    "Accueil": "الرئيسية",
    "Langue": "اللغة",
    "Afficher en français": "العرض بالفرنسية",
    "Afficher en arabe": "العرض بالعربية",

    # Page publique et connexion
    "Gestion scolaire : inscriptions, notes, finances, emploi du temps et communication.":
        "التسيير المدرسي: التسجيل، الدرجات، المالية، جدول الحصص والتواصل.",
    "Se connecter": "الدخول",
    "Créer un compte": "إنشاء حساب",
    "Vous avez reçu un bulletin, un certificat ou un reçu ?": "استلمتم كشف درجات أو شهادة أو وصلًا؟",
    "Vérifier qu'il est authentique": "تحققوا من صحته",
    "Email ou matricule": "البريد الإلكتروني أو رقم التسجيل",
    "Mot de passe": "كلمة المرور",
    "Mot de passe oublié ?": "نسيتم كلمة المرور؟",
    "Nouveau ici ?": "جديد هنا؟",
    "Afficher ou masquer le mot de passe": "إظهار كلمة المرور أو إخفاؤها",

    # Tableau de bord
    "Bonjour, {prenom}": "مرحبًا، {prenom}",
    "année scolaire {annee}": "السنة الدراسية {annee}",
    "Encaisser un paiement": "تسجيل دفعة",
    "Inscrire un élève": "تسجيل تلميذ",
    "Sauvegarde recommandée.": "يُنصح بأخذ نسخة احتياطية.",
    "Télécharger une sauvegarde maintenant": "تنزيل نسخة احتياطية الآن",
    "Indicateurs clés": "المؤشرات الرئيسية",
    "Encaissé en {mois}": "المحصل في شهر {mois}",
    "sur": "من",
    "à": "على الساعة",
    "Inscription": "التسجيل",
    "Tranche 1 (novembre)": "القسط الأول (نوفمبر)",
    "Tranche 2 (février)": "القسط الثاني (فبراير)",
    "Mes enfants": "أبنائي",
    "Mon EDT": "جدول حصصي",
    "par rapport à l'an dernier": "مقارنة بالسنة الماضية",
    "Depuis le début du mois": "منذ بداية الشهر",
    "Recouvrement de l'année": "نسبة التحصيل السنوية",
    "du total attendu": "من المبلغ المتوقع",
    "Reste": "المتبقي",
    "Élèves inscrits": "التلاميذ المسجلون",
    "{filles} filles · {garcons} garçons · {classes} classes": "{filles} بنات · {garcons} بنين · {classes} أقسام",
    "Absents aujourd'hui": "الغائبون اليوم",
    "dont {n} non justifiés": "منهم {n} دون مبرر",
    "Aucune absence signalée": "لا توجد غيابات مسجلة",
    "Échéancier de la scolarité": "جدول أقساط التمدرس",
    "Voir les retards": "عرض المتأخرات",
    "Montant encaissé par rapport au montant attendu, pour chaque échéance.":
        "المبلغ المحصل مقارنة بالمبلغ المتوقع لكل قسط.",
    "limite le {date}": "آخر أجل {date}",
    "{paye} sur {attendu}": "{paye} من {attendu}",
    "Encaissé": "المحصل",
    "Reste à encaisser": "المتبقي للتحصيل",
    "À traiter": "للمعالجة",
    "Rien en attente. Tout est à jour.": "لا شيء في الانتظار. كل شيء محدث.",
    "Recouvrement par classe": "التحصيل حسب القسم",
    "Toutes les statistiques": "كل الإحصائيات",
    "Part du total dû déjà payée. Les classes les plus en retard en premier.":
        "نسبة المبلغ المستحق المدفوعة. الأقسام الأكثر تأخرًا أولًا.",
    "Classe": "القسم",
    "Taux": "النسبة",
    "Reste dû": "المتبقي",
    "État": "الحالة",
    "Bon": "جيد",
    "À suivre": "للمتابعة",
    "Critique": "حرج",
    "Aucun frais de scolarité n'est encore fixé pour cette année.": "لم تُحدد رسوم التمدرس لهذه السنة بعد.",
    "Absences du jour": "غيابات اليوم",
    "Faire l'appel": "تسجيل الحضور",
    "Aucune absence n'a été signalée aujourd'hui.": "لم يُسجل أي غياب اليوم.",
    "{n} absent(s)": "{n} غائب",
    "sur {n}": "من {n}",
    "Derniers paiements": "آخر الدفعات",
    "Journal de caisse": "سجل الصندوق",
    "Élève": "التلميذ",
    "Objet": "الموضوع",
    "Mode": "طريقة الدفع",
    "Montant": "المبلغ",
    "Reçu": "الوصل",
    "Date": "التاريخ",
    "Aucun paiement enregistré pour le moment.": "لا توجد دفعات مسجلة حاليًا.",
    "Guides d'utilisation": "أدلة الاستخدام",
    "Lire le guide →": "← قراءة الدليل",
    "Espèces": "نقدًا",
    "Mobile Money": "الدفع عبر الهاتف",
    "Virement": "تحويل بنكي",

    # Tâches « À traiter »
    "Familles en retard de paiement": "أسر متأخرة في الدفع",
    "Une échéance dépassée n'est pas soldée": "قسط تجاوز أجله ولم يُسدد",
    "Élèves en alerte": "تلاميذ في وضعية تنبيه",
    "Absences non justifiées répétées": "غيابات متكررة دون مبرر",
    "Parents à prévenir": "أولياء يجب إخطارهم",
    "Absences non justifiées du jour, à signaler sur WhatsApp": "غيابات اليوم دون مبرر، للإبلاغ عنها عبر واتساب",
    "Comptes à valider": "حسابات للمصادقة",
    "Demandes d'inscription en attente": "طلبات تسجيل في الانتظار",
    "Messages de parents": "رسائل الأولياء",
    "Conversations avec un message non lu": "محادثات بها رسالة غير مقروءة",

    # Vérification d'un document
    "Vérifier un document": "التحقق من وثيقة",
    "Document authentique": "وثيقة أصلية",
    "Document annulé par l'école": "وثيقة ألغتها المؤسسة",
    "Ce document a bien été émis, mais l'école l'a annulé depuis. Il n'est plus valable.":
        "صدرت هذه الوثيقة فعلًا، لكن المؤسسة ألغتها لاحقًا. لم تعد صالحة.",
    "Il a été émis par {ecole} le {date}.": "أصدرتها {ecole} بتاريخ {date}.",
    "Comparez avec le papier. Si une seule information diffère, le document a été modifié après son émission.":
        "قارنوا مع النسخة الورقية. إذا اختلفت معلومة واحدة، فقد عُدلت الوثيقة بعد إصدارها.",
    "Date d'émission": "تاريخ الإصدار",
    "Matricule": "رقم التسجيل",
    "Référence": "المرجع",
    "Aucun document ne porte ce code": "لا توجد وثيقة تحمل هذا الرمز",
    "Vérifiez la saisie. Si le code est correct, ce document n'a pas été émis par une école de {plateforme} : il peut s'agir d'un faux.":
        "تحققوا من الرمز المُدخل. إذا كان صحيحًا، فهذه الوثيقة لم تصدرها أي مؤسسة على {plateforme}، وقد تكون مزورة.",
    "Chaque bulletin, certificat, attestation et reçu porte un QR code et un code de 12 caractères. Scannez le QR code avec l'appareil photo de votre téléphone, ou saisissez le code ci-dessous.":
        "يحمل كل كشف درجات وشهادة ووصل رمز QR ورمزًا من 12 حرفًا. امسحوا رمز QR بكاميرا الهاتف، أو أدخلوا الرمز أدناه.",
    "Code du document": "رمز الوثيقة",
    "Vérifier": "تحقق",
    "Ex. K7QF-3M9X-PA2D": "مثال: K7QF-3M9X-PA2D",

    # Relances WhatsApp
    "Le message est déjà rédigé : cliquez sur un parent, WhatsApp s'ouvre, il ne reste qu'à appuyer sur Envoyer.":
        "الرسالة جاهزة: انقروا على اسم الولي، يُفتح واتساب، ولا يبقى سوى الضغط على إرسال.",
    "Absences non justifiées": "غيابات دون مبرر",
    "Jour": "اليوم",
    "Prévenu à {heure}": "تم الإخطار على الساعة {heure}",
    "par {nom}": "من طرف {nom}",
    "À prévenir": "للإخطار",
    "Aucune absence non justifiée ce jour-là.": "لا توجد غيابات دون مبرر في هذا اليوم.",
    "Paiements en retard": "دفعات متأخرة",
    "Soldes à régler": "أرصدة للتسديد",
    "Seulement les retards": "المتأخرات فقط",
    "Tous les soldes non réglés": "كل الأرصدة غير المسددة",
    "Élèves dont une date limite de paiement est dépassée.": "تلاميذ تجاوزوا آخر أجل للدفع.",
    "Élèves qui ont encore un montant à payer, les plus en retard en premier.":
        "تلاميذ لا يزال عليهم مبلغ للدفع، الأكثر تأخرًا أولًا.",
    "reste {montant}": "المتبقي {montant}",
    "dont {montant} en retard": "منها {montant} متأخرة",
    "Relancé le {date}": "تم التذكير بتاريخ {date}",
    "Toutes les familles sont à jour.": "كل الأسر في وضعية سليمة.",
    "Aucun paiement en retard. Si aucune date limite n'est fixée, rien ne peut être en retard : voir Administration › Établissement.":
        "لا توجد دفعات متأخرة. إذا لم يُحدد أي أجل للدفع فلا يمكن احتساب أي تأخير: انظر الإدارة › المؤسسة.",
    "Aucun numéro mobile valide dans le dossier": "لا يوجد رقم هاتف محمول صالح في الملف",
    "Ouvrir WhatsApp avec le message prêt à envoyer": "فتح واتساب مع رسالة جاهزة للإرسال",
    "Téléphone du dossier": "هاتف الملف",
    "Contact d'urgence": "جهة الاتصال في الطوارئ",
    "urgence": "طوارئ",
    "← Précédent": "السابق →",
    "Suivant →": "← التالي",
    "page {page}/{total}": "الصفحة {page}/{total}",
}

# --- Écrans de gestion (oct. 2026) --------------------------------------------
# Textes des formulaires, listes et messages de confirmation. Les fragments
# (« Parents ( », « Maximum de ») entourent une valeur affichée par le modèle.

INTERFACE.update({
    # Messages de confirmation et d'erreur
    "L'accès de cet établissement est suspendu. Contacte l'administrateur de la plateforme.": "تم تعليق وصول هذه المؤسسة. يرجى الاتصال بمسؤول المنصة.",
    "Ce compte n'est plus actif. Contacte l'école si besoin.": "هذا الحساب لم يعد نشطًا. يرجى الاتصال بالمدرسة عند الحاجة.",
    "Compte créé. Il sera activé après vérification de ton dossier par le secrétariat.": "تم إنشاء الحساب. سيتم تفعيله بعد أن تتحقق الأمانة من ملفكم.",
    "Identifiant ou mot de passe incorrect.": "اسم المستخدم أو كلمة المرور غير صحيحة.",
    "Votre compte est en attente de validation par le secrétariat.": "حسابكم في انتظار موافقة الأمانة.",
    "Votre demande de compte a été refusée. Contactez l'école.": "تم رفض طلب حسابكم. يرجى الاتصال بالمدرسة.",
    "Ce compte a été verrouillé. Contacte le développeur ou la direction pour le débloquer.": "تم قفل هذا الحساب. يرجى الاتصال بالمطوّر أو الإدارة لفتحه.",
    "Code invalide ou expiré. Demande-en un nouveau si besoin.": "الرمز غير صالح أو منتهي الصلاحية. اطلبوا رمزًا جديدًا عند الحاجة.",
    "Email vérifié. Ta demande de compte est transmise au secrétariat pour validation.": "تم التحقق من البريد الإلكتروني. أُرسل طلب حسابكم إلى الأمانة للموافقة.",
    "Un email de réinitialisation vient de t'être envoyé.": "أُرسل إليكم بريد إلكتروني لإعادة تعيين كلمة المرور.",
    "Si un compte existe, un lien de réinitialisation vient d'être généré.": "إذا كان الحساب موجودًا، فقد تم إنشاء رابط لإعادة التعيين.",
    "Ce lien de réinitialisation est invalide ou a expiré.": "رابط إعادة التعيين هذا غير صالح أو منتهي الصلاحية.",
    "Les mots de passe ne correspondent pas.": "كلمتا المرور غير متطابقتين.",
    "Le mot de passe doit faire au moins 8 caractères.": "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.",
    "Mot de passe réinitialisé. Tu peux te connecter.": "تمت إعادة تعيين كلمة المرور. يمكنكم تسجيل الدخول.",
    "La configuration initiale a déjà été faite — connecte-toi normalement.": "تم الإعداد الأولي مسبقًا، سجّلوا الدخول بشكل عادي.",
    "Compte développeur créé. Tu peux te connecter.": "تم إنشاء حساب المطوّر. يمكنكم تسجيل الدخول.",
    "Merci de remplir le titre, le type et de choisir un fichier.": "يرجى ملء العنوان والنوع واختيار ملف.",
    "Type de fichier non autorisé (document, image ou vidéo uniquement).": "نوع الملف غير مسموح به (وثيقة أو صورة أو فيديو فقط).",
    "Ressource ajoutée.": "تمت إضافة المورد.",
    "Ce fichier n'est plus disponible — il a été ajouté avant la mise en place du stockage permanent. Merci de le réimporter.": "هذا الملف لم يعد متاحًا، فقد أُضيف قبل اعتماد التخزين الدائم. يرجى استيراده من جديد.",
    "Merci de choisir un type et au moins un fichier.": "يرجى اختيار نوع وملف واحد على الأقل.",
    "Aucune ressource téléchargeable à exporter (les ressources verrouillées ou sans fichier ne sont jamais incluses).": "لا توجد موارد قابلة للتنزيل للتصدير (الموارد المقفلة أو التي بلا ملف لا تُدرج أبدًا).",
    "Mouvement de caisse enregistré.": "تم تسجيل حركة الصندوق.",
    "Cette ligne vient d'un paiement de scolarité : corrige-la depuis la fiche Finances de l'élève.": "هذا السطر ناتج عن دفع رسوم دراسية: يُصحَّح من البطاقة المالية للتلميذ.",
    "Mouvement de caisse corrigé.": "تم تصحيح حركة الصندوق.",
    "Cette ligne vient d'un paiement de scolarité : supprime le paiement depuis Finances plutôt que la ligne de Caisse.": "هذا السطر ناتج عن دفع رسوم دراسية: احذفوا الدفعة من المالية بدلًا من سطر الصندوق.",
    "Mouvement de caisse supprimé.": "تم حذف حركة الصندوق.",
    "Merci de choisir un élève, un montant valide, un mode et une échéance.": "يرجى اختيار تلميذ ومبلغ صحيح وطريقة دفع وقسط.",
    "Ce niveau ne fait pas partie de ton cycle de supervision.": "هذا المستوى لا يدخل ضمن المرحلة التي تشرفون عليها.",
    "Montants invalides.": "مبالغ غير صحيحة.",
    "Merci d'indiquer l'année scolaire à créer (ex : 2027-2028).": "يرجى تحديد السنة الدراسية المراد إنشاؤها (مثال: 2027-2028).",
    "Merci de remplir tous les champs (et de choisir un destinataire autorisé).": "يرجى ملء جميع الحقول (واختيار مرسَل إليه مسموح به).",
    "Type de pièce jointe non autorisé (document ou image uniquement).": "نوع المرفق غير مسموح به (وثيقة أو صورة فقط).",
    "Annonce publiée.": "تم نشر الإعلان.",
    "Annonce supprimée.": "تم حذف الإعلان.",
    "Tu ne peux pas verrouiller ton propre compte.": "لا يمكنكم قفل حسابكم الخاص.",
    "Rôle invalide.": "دور غير صالح.",
    "Statut invalide.": "حالة غير صالحة.",
    "Seul un administrateur de la plateforme peut attribuer ce rôle.": "لا يمكن إسناد هذا الدور إلا من طرف مسؤول المنصة.",
    "Tu ne peux pas changer ton propre rôle depuis cet écran — demande à un autre développeur ou fondateur de le faire.": "لا يمكنكم تغيير دوركم من هذه الشاشة، اطلبوا ذلك من مطوّر أو مؤسس آخر.",
    "Tu ne peux pas supprimer ton propre compte depuis cet écran.": "لا يمكنكم حذف حسابكم الخاص من هذه الشاشة.",
    "Permissions mises à jour.": "تم تحديث الصلاحيات.",
    "Paramètres enregistrés.": "تم حفظ الإعدادات.",
    "Dossier mis à jour.": "تم تحديث الملف.",
    "Le nom et la classe sont obligatoires.": "الاسم والقسم إلزاميان.",
    "Classe introuvable.": "القسم غير موجود.",
    "Compte introuvable ou pas encore actif.": "الحساب غير موجود أو غير نشط بعد.",
    "Aucune classe supérieure n'est encore définie après cette classe.": "لم يُحدَّد بعد قسم أعلى بعد هذا القسم.",
    "Vous n'avez pas le droit de modifier l'emploi du temps.": "ليس لديكم صلاحية تعديل جدول الحصص.",
    "Enseignant introuvable.": "المدرّس غير موجود.",
    "Merci de remplir tous les champs.": "يرجى ملء جميع الحقول.",
    "L'heure de fin doit être après l'heure de début.": "يجب أن تكون ساعة النهاية بعد ساعة البداية.",
    "Créneau ajouté.": "تمت إضافة الحصة.",
    "Format d'export inconnu.": "صيغة تصدير غير معروفة.",
    "Merci de choisir un compte enseignant.": "يرجى اختيار حساب مدرّس.",
    "Profil enseignant créé.": "تم إنشاء ملف المدرّس.",
    "Merci de choisir une classe et une matière.": "يرجى اختيار قسم ومادة.",
    "Affectation ajoutée.": "تمت إضافة التعيين.",
    "La remise doit être comprise entre 0 et 100 %.": "يجب أن يكون التخفيض بين 0 و100 %.",
    "Le libellé et un montant valide sont obligatoires.": "البيان ومبلغ صحيح إلزاميان.",
    "Impossible de supprimer ce frais : des paiements y sont déjà rattachés.": "لا يمكن حذف هذه الرسوم: توجد دفعات مرتبطة بها.",
    "Frais supprimé.": "تم حذف الرسوم.",
    "Rien à relancer, le solde est déjà à jour.": "لا حاجة للتذكير، الرصيد مسدَّد.",
    "Aucun parent lié à ce dossier pour recevoir la relance.": "لا يوجد ولي أمر مرتبط بهذا الملف لاستلام التذكير.",
    "Merci de saisir un montant valide (sans centimes), un mode de paiement et une échéance.": "يرجى إدخال مبلغ صحيح (بدون كسور) وطريقة دفع وقسط.",
    "Le mot de passe actuel est incorrect.": "كلمة المرور الحالية غير صحيحة.",
    "Le nouveau mot de passe doit faire au moins 8 caractères.": "يجب أن تتكون كلمة المرور الجديدة من 8 أحرف على الأقل.",
    "Les deux saisies du nouveau mot de passe ne correspondent pas.": "الإدخالان لكلمة المرور الجديدة غير متطابقين.",
    "Le nouveau mot de passe doit être différent de l'actuel.": "يجب أن تختلف كلمة المرور الجديدة عن الحالية.",
    "Mot de passe modifié.": "تم تغيير كلمة المرور.",
    "Genre enregistré.": "تم حفظ الجنس.",
    "Numéro invalide — un mobile tchadien a 8 chiffres et commence par 6 ou 9 (ex. 66 12 34 56).": "رقم غير صالح: رقم الهاتف التشادي يتكون من 8 أرقام ويبدأ بـ 6 أو 9 (مثال: 66 12 34 56).",
    "Merci de choisir l'opérateur.": "يرجى اختيار المشغّل.",
    "Numéro ajouté.": "تمت إضافة الرقم.",
    "Numéro supprimé.": "تم حذف الرقم.",
    "Ce code n'a pas le bon format. Il compte 12 caractères, par exemple K7QF-3M9X-PA2D.": "صيغة هذا الرمز غير صحيحة. يتكون من 12 حرفًا، مثل K7QF-3M9X-PA2D.",
    "Le message ne peut pas être vide.": "لا يمكن أن تكون الرسالة فارغة.",
    "Message envoyé à l'école.": "تم إرسال الرسالة إلى المدرسة.",
    "Réponse envoyée.": "تم إرسال الرد.",
    "Merci de choisir une matière que vous enseignez et un trimestre valide.": "يرجى اختيار مادة تدرّسونها وفصلًا صحيحًا.",
    "Le titre, le type et la date de l'évaluation sont obligatoires.": "عنوان التقييم ونوعه وتاريخه إلزامية.",
    "Le coefficient doit être compris entre 0,5 et 10.": "يجب أن يكون المعامل بين 0,5 و10.",
    "Évaluation supprimée, avec ses notes.": "تم حذف التقييم مع درجاته.",
    "Appréciation enregistrée.": "تم حفظ الملاحظة.",
    "Coefficients enregistrés.": "تم حفظ المعاملات.",
    "Établissement mis à jour.": "تم تحديث المؤسسة.",
    "Confirmation incorrecte : rien n'a été modifié.": "تأكيد غير صحيح: لم يتم تعديل أي شيء.",
    "Choisis le fichier de sauvegarde (.zip).": "اختاروا ملف النسخة الاحتياطية (.zip).",
    "Ce fichier n'est pas une archive .zip valide.": "هذا الملف ليس أرشيف .zip صالحًا.",
    "Ce salaire est déjà marqué comme payé.": "هذا الراتب مسجّل كمدفوع مسبقًا.",
    "Ligne de salaire supprimée (et sa dépense de Caisse associée si elle existait).": "تم حذف سطر الراتب (ومصروف الصندوق المرتبط به إن وُجد).",
    "Cette classe ne relève pas de ton cycle.": "هذا القسم لا يدخل ضمن مرحلتكم.",
    "Merci de choisir une matière que vous enseignez et de préciser le chapitre.": "يرجى اختيار مادة تدرّسونها وتحديد الفصل.",
    "Progression enregistrée.": "تم حفظ التقدّم.",
    "Merci de renseigner au moins le nom du candidat et la classe demandée.": "يرجى إدخال اسم المترشح والقسم المطلوب على الأقل.",
    "Cette classe ne fait pas partie de ton cycle de supervision.": "هذا القسم لا يدخل ضمن المرحلة التي تشرفون عليها.",

    # Éléments communs
    "Autre montant…": "مبلغ آخر…",
    "Montant exact": "المبلغ بالضبط",
    "Supprimer": "حذف",
    "Modifier": "تعديل",
    "Corriger": "تصحيح",
    "Enregistrer": "حفظ",
    "Envoyer": "إرسال",
    "Ajouter": "إضافة",
    "Créer": "إنشاء",
    "Voir": "عرض",
    "Ouvrir": "فتح",
    "Filtrer": "تصفية",
    "Chercher": "بحث",
    "Rechercher": "بحث",
    "Télécharger": "تنزيل",
    "Importer": "استيراد",
    "Valider": "تأكيد",
    "Détail": "التفاصيل",
    "Détails": "التفاصيل",
    "Retour au tableau de bord": "العودة إلى لوحة القيادة",
    "Tous": "الكل",
    "Toutes": "الكل",
    "Toutes les classes": "كل الأقسام",
    "Tous les élèves": "كل التلاميذ",
    "Nom": "الاسم",
    "Nom complet": "الاسم الكامل",
    "Prénom": "الاسم الشخصي",
    "Email": "البريد الإلكتروني",
    "Email :": "البريد الإلكتروني:",
    "Téléphone": "الهاتف",
    "Genre": "الجنس",
    "Genre :": "الجنس:",
    "Sexe": "الجنس",
    "Masculin": "ذكر",
    "Féminin": "أنثى",
    "Date de naissance": "تاريخ الميلاد",
    "Statut": "الحالة",
    "Rôle": "الدور",
    "Description": "الوصف",
    "Fichier": "الملف",
    "Photo": "الصورة",
    "Libellé": "البيان",
    "Observation": "ملاحظة",
    "Motif": "السبب",
    "Total": "المجموع",
    "Total :": "المجموع:",
    "Note": "الدرجة",
    "Notes": "الدرجات",
    "Moyenne": "المعدل",
    "Seuil": "العتبة",
    "Année": "السنة",
    "Année scolaire": "السنة الدراسية",
    "Mois": "الشهر",
    "Trimestre": "الفصل",
    "Période": "الفترة",
    "Matière": "المادة",
    "Type": "النوع",
    "Titre": "العنوان",
    "Niveau": "المستوى",
    "Choisir un niveau": "اختيار مستوى",
    "Choisir une classe": "اختيار قسم",
    "Choisir…": "اختيار…",
    "— Choisir —": "— اختيار —",
    "Ville": "المدينة",
    "Pays": "البلد",
    "Pages": "الصفحات",
    "Historique": "السجل",
    "Utilisateur": "المستخدم",
    "Action": "الإجراء",
    "Enseignant": "المدرّس",
    "Parent": "ولي الأمر",
    "Personnel": "الموظفون",
    "Responsable": "المسؤول",
    "Destinataires": "المرسَل إليهم",
    "Décision": "القرار",
    "Décision :": "القرار:",
    "Mention": "التقدير",
    "Rang": "الرتبة",
    "Appréciation": "الملاحظة",
    "Coefficient": "المعامل",
    "Coefficients": "المعاملات",
    "Coef.": "المعامل",
    "Points": "النقاط",
    "Échéance": "القسط",
    "Mode de paiement": "طريقة الدفع",
    "Date limite": "آخر أجل",
    "Date limite de paiement": "آخر أجل للدفع",
    "Frais": "الرسوم",
    "Frais annexes": "الرسوم الإضافية",
    "Remise": "التخفيض",
    "Payé": "مدفوع",
    "Dû": "المستحق",
    "Attendu": "المتوقع",
    "Solde": "الرصيد",
    "Recette": "إيراد",
    "Dépense": "مصروف",
    "auto": "تلقائي",
    "Complet": "مكتمل",
    "Incomplet": "غير مكتمل",
    "En retard": "متأخر",
    "Absent": "غائب",
    "Justifiée": "مبرَّر",
    "Effectif": "العدد",
    "Garçons": "الذكور",
    "Filles": "الإناث",
    "(facultatif)": "(اختياري)",
    "M": "ذ",
    "F": "أ",

    # Erreurs
    "Accès refusé": "الوصول مرفوض",
    "Tu n'as pas les droits nécessaires pour accéder à cette page.": "ليست لديكم الصلاحيات اللازمة للوصول إلى هذه الصفحة.",
    "Page introuvable": "الصفحة غير موجودة",
    "Cette page n'existe pas, ou a été déplacée.": "هذه الصفحة غير موجودة أو تم نقلها.",
    "Fichier trop volumineux": "الملف كبير جدًا",
    "Le fichier envoyé dépasse la taille maximale autorisée (20 Mo). Réduis sa taille et réessaie.": "يتجاوز الملف المرسل الحجم الأقصى المسموح به (20 ميغابايت). قلّصوا حجمه وأعيدوا المحاولة.",
    "Trop de tentatives": "محاولات كثيرة جدًا",
    "Trop d'essais en peu de temps. Attends quelques minutes avant de réessayer — c'est une protection contre les tentatives de connexion répétées.": "محاولات كثيرة في وقت قصير. انتظروا بضع دقائق قبل إعادة المحاولة، فهذه حماية من محاولات الدخول المتكررة.",
    "Erreur": "خطأ",
    "Une erreur est survenue": "حدث خطأ",
    "Le problème a été enregistré. Réessaie dans quelques instants, ou contacte le développeur si ça persiste.": "تم تسجيل المشكلة. أعيدوا المحاولة بعد لحظات، أو اتصلوا بالمطوّر إذا استمرت.",

    # Absences et alertes
    "Absences non justifiées :": "الغيابات غير المبررة:",
    "Aucune absence enregistrée.": "لا توجد غيابات مسجلة.",
    "Absences —": "الغيابات —",
    "Enregistrer les absences": "حفظ الغيابات",
    "Absences répétées (": "غيابات متكررة (",
    "ou plus, non justifiées)": "أو أكثر، غير مبررة)",
    "Voir le détail": "عرض التفاصيل",
    "Moyenne sous le seuil de réussite": "معدل دون عتبة النجاح",
    "Aucun élève au-delà du seuil pour l'instant.": "لا يوجد تلميذ فوق العتبة حاليًا.",
    "Aucun élève sous le seuil pour l'instant.": "لا يوجد تلميذ دون العتبة حاليًا.",

    # Assistant
    "Ta question": "سؤالكم",
    "Demander": "اسأل",
    "Réponse :": "الجواب:",
    "Exemples de questions que tu peux poser": "أمثلة على أسئلة يمكنكم طرحها",

    # Inscription, mot de passe
    "Demande envoyée.": "تم إرسال الطلب.",
    "Votre compte sera activé dès validation par le secrétariat.": "سيتم تفعيل حسابكم بمجرد موافقة الأمانة.",
    "Je suis…": "أنا…",
    "Choisir un profil": "اختيار الصفة",
    "Personnel de l'école (précisé après validation)": "من موظفي المدرسة (يُحدَّد بعد الموافقة)",
    "Profession": "المهنة",
    "(obligatoire, unique)": "(إلزامي، فريد)",
    "Envoyer ma demande": "إرسال طلبي",
    "Déjà un compte ? Se connecter": "لديكم حساب؟ تسجيل الدخول",
    "Mot de passe oublié": "نسيت كلمة المرور",
    "Lien de réinitialisation (valable 30 minutes) :": "رابط إعادة التعيين (صالح لمدة 30 دقيقة):",
    "Aucun service d'envoi d'email n'est encore configuré sur cette installation, le lien est donc affiché ici directement. Une fois un service d'email réel branché, ce lien sera envoyé automatiquement à l'adresse indiquée.": "لم تُضبط بعد أي خدمة لإرسال البريد الإلكتروني في هذا التثبيت، لذلك يظهر الرابط هنا مباشرة. بعد ربط خدمة بريد فعلية، سيُرسل الرابط تلقائيًا إلى العنوان المحدد.",
    "Indique ton email, ou ton matricule si tu es élève (l'email généré à l'inscription n'est pas consultable — le lien partira alors chez ton/tes parent(s) lié(s)).": "أدخلوا بريدكم الإلكتروني، أو رقم التسجيل إن كنتم تلاميذ (يُرسل الرابط حينئذ إلى أولياء الأمور المرتبطين).",
    "Envoyer le lien": "إرسال الرابط",
    "Retour à la connexion": "العودة إلى تسجيل الدخول",
    "Première configuration": "الإعداد الأولي",
    "Créer le compte développeur": "إنشاء حساب المطوّر",
    "Choisir un nouveau mot de passe": "اختيار كلمة مرور جديدة",
    "Confirmer le mot de passe": "تأكيد كلمة المرور",
    "Réinitialiser": "إعادة التعيين",
    "Vérification de l'email": "التحقق من البريد الإلكتروني",
    "Vérifie ton email": "تحققوا من بريدكم الإلكتروني",
    "Un code à 6 chiffres a été envoyé à": "أُرسل رمز من 6 أرقام إلى",
    "pour confirmer ton adresse.": "لتأكيد عنوانكم.",
    "Code de vérification": "رمز التحقق",
    "Renvoyer le code": "إعادة إرسال الرمز",

    # Bibliothèque
    "Importer des ressources": "استيراد موارد",
    "Importer plusieurs fichiers": "استيراد عدة ملفات",
    "Type (appliqué à tous les fichiers)": "النوع (يُطبَّق على كل الملفات)",
    "Fichiers (plusieurs à la fois)": "الملفات (عدة ملفات دفعة واحدة)",
    "Consultation sur place uniquement (non téléchargeable), pour tous les fichiers importés": "للاطلاع في عين المكان فقط (غير قابل للتنزيل)، لكل الملفات المستوردة",
    "Bibliothèque numérique": "المكتبة الرقمية",
    "Ajouter une ressource": "إضافة مورد",
    "(.zip)": "(.zip)",
    "Filtrer par type": "التصفية حسب النوع",
    "Tous les types": "كل الأنواع",
    "Consultation sur place": "للاطلاع في عين المكان",
    "Consulter en ligne": "الاطلاع عبر الإنترنت",
    "Supprimer définitivement cette ressource ?": "حذف هذا المورد نهائيًا؟",
    "Aucune ressource pour l'instant.": "لا توجد موارد حاليًا.",
    "Consultation sur place uniquement (non téléchargeable)": "للاطلاع في عين المكان فقط (غير قابل للتنزيل)",

    # Caisse
    "Paiement de scolarité": "دفع الرسوم الدراسية",
    "Autre recette ou dépense": "إيراد أو مصروف آخر",
    "Total recettes": "مجموع الإيرادات",
    "Total dépenses": "مجموع المصروفات",
    "Solde actuel": "الرصيد الحالي",
    "Reçu PDF": "الوصل (PDF)",
    "Supprimer ce mouvement de caisse ?": "حذف حركة الصندوق هذه؟",
    "Caisse générale": "الصندوق العام",
    "Aucun mouvement de caisse pour l'instant.": "لا توجد حركات في الصندوق حاليًا.",
    "Corriger un mouvement de caisse": "تصحيح حركة صندوق",
    "Corriger le mouvement": "تصحيح الحركة",
    "Enregistrer la correction": "حفظ التصحيح",
    "Nouveau mouvement de caisse": "حركة صندوق جديدة",
    "Recette (si entrée d'argent)": "إيراد (في حالة دخول مال)",
    "Dépense (si sortie d'argent)": "مصروف (في حالة خروج مال)",
    "Nouveau paiement officiel": "دفعة رسمية جديدة",
    "Enregistrer le paiement": "حفظ الدفعة",

    # Classes
    "Démarrer une année scolaire": "بدء سنة دراسية",
    "Nouvelle année scolaire": "سنة دراسية جديدة",
    "Reprendre l'échéancier de frais depuis": "نقل جدول الرسوم من",
    "— Ne pas reprendre —": "— بدون نقل —",
    "Créer les classes CP1 à 3ème pour cette année": "إنشاء الأقسام من CP1 إلى 3ème لهذه السنة",
    "année": "السنة",
    "— archive": "— أرشيف",
    "(en cours)": "(الجارية)",
    "Nouvelle classe": "قسم جديد",
    "Démarrer une nouvelle année scolaire": "بدء سنة دراسية جديدة",
    "élève(s) · total annuel": "تلميذ · المجموع السنوي",
    "Mettre à jour le groupe": "تحديث المجموعة",
    "Aucune classe pour l'instant.": "لا توجد أقسام حاليًا.",
    "Nom de la classe": "اسم القسم",
    "Frais d'inscription": "رسوم التسجيل",
    "Frais tranche 1 (novembre)": "رسوم القسط 1 (نوفمبر)",
    "Frais tranche 2 (février)": "رسوم القسط 2 (فبراير)",
    "Créer la classe": "إنشاء القسم",

    # Communication et messagerie
    "← Toutes les annonces": "→ كل الإعلانات",
    "Nouvelle annonce": "إعلان جديد",
    "Date précise": "تاريخ محدد",
    "Télécharger la pièce jointe": "تنزيل المرفق",
    "Supprimer cette annonce ?": "حذف هذا الإعلان؟",
    "Aucune annonce pour l'instant.": "لا توجد إعلانات حاليًا.",
    "Contenu": "المحتوى",
    "Pièce jointe": "المرفق",
    "Publier": "نشر",
    "Fil —": "المحادثة —",
    "Discussion avec": "محادثة مع",
    "← Tous les fils": "→ كل المحادثات",
    "Réponse": "الرد",
    "Aucun message dans ce fil.": "لا توجد رسائل في هذه المحادثة.",
    "Mes messages avec l'école": "رسائلي مع المدرسة",
    "Ton message": "رسالتكم",
    "Envoyer à l'école": "إرسال إلى المدرسة",
    "Aucun message pour l'instant — écris ci-dessous pour contacter l'école.": "لا توجد رسائل حاليًا، اكتبوا أدناه للتواصل مع المدرسة.",
    "Messagerie": "المراسلات",
    "non lu(s)": "غير مقروءة",
    "Ouvrir le fil": "فتح المحادثة",
    "Aucun message reçu pour l'instant.": "لم تصل أي رسالة حاليًا.",

    # Espace développeur et paramètres
    "Journal d'actions": "سجل العمليات",
    "Type d'action": "نوع العملية",
    "Aucune action enregistrée pour l'instant.": "لا توجد عمليات مسجلة حاليًا.",
    "Journal des emails": "سجل الرسائل الإلكترونية",
    "Journal des emails envoyés": "سجل الرسائل الإلكترونية المرسلة",
    "Réussis": "ناجحة",
    "Échecs": "فاشلة",
    "Destinataire(s)": "المرسَل إليه",
    "Sujet": "الموضوع",
    "Aucun email envoyé pour l'instant.": "لم يُرسل أي بريد إلكتروني حاليًا.",
    "Paramètres de l'établissement": "إعدادات المؤسسة",
    "Signataire des documents": "موقّع الوثائق",
    "Qualité": "الصفة",
    "Documents bilingues français · arabe": "وثائق ثنائية اللغة فرنسية · عربية",
    "Bulletins, certificats, attestations et reçus en français et en arabe": "كشوف الدرجات والشهادات والإفادات والوصولات بالفرنسية والعربية",
    "Nom de l'établissement en arabe": "اسم المؤسسة بالعربية",
    "Ville en arabe": "المدينة بالعربية",
    "Dates limites de paiement": "آجال الدفع",
    "Tranche 1": "القسط 1",
    "Tranche 2": "القسط 2",
    "Permissions": "الصلاحيات",
    "Permissions par rôle": "الصلاحيات حسب الدور",
    "Enregistrer les permissions": "حفظ الصلاحيات",
    "Espace développeur": "فضاء المطوّر",
    "Gérer les permissions par module": "إدارة الصلاحيات حسب الوحدة",
    "Télécharger une sauvegarde complète (.zip)": "تنزيل نسخة احتياطية كاملة (.zip)",
    "Paramètres de l'établissement (nom du directeur sur les documents)": "إعدادات المؤسسة (اسم المدير على الوثائق)",
    "Consulter le journal d'actions": "الاطلاع على سجل العمليات",
    "Consulter le journal des emails envoyés": "الاطلاع على سجل الرسائل الإلكترونية المرسلة",
    "Rechercher un nom ou un email…": "البحث عن اسم أو بريد إلكتروني…",
    "Créé le": "أُنشئ في",

    # Dossier élève
    "État civil": "الحالة المدنية",
    "Lieu de naissance": "مكان الميلاد",
    "Adresse (quartier)": "العنوان (الحي)",
    "Famille": "الأسرة",
    "Nom du père": "اسم الأب",
    "Nom de la mère": "اسم الأم",
    "Téléphone du parent ou tuteur": "هاتف ولي الأمر أو الوصي",
    "Personne à prévenir en cas d'urgence": "الشخص الذي يُتصل به في حالة الطوارئ",
    "Téléphone d'urgence": "هاتف الطوارئ",
    "Retirer la photo": "إزالة الصورة",
    "Modifier le dossier": "تعديل الملف",
    "Certificat de scolarité (PDF)": "شهادة مدرسية (PDF)",
    "Attestation de fréquentation (PDF)": "إفادة حضور (PDF)",
    "Naissance": "الميلاد",
    "Nationalité": "الجنسية",
    "Adresse": "العنوان",
    "Père": "الأب",
    "Mère": "الأم",
    "Téléphone parent": "هاتف ولي الأمر",
    "Urgence": "الطوارئ",
    "École d'origine": "المدرسة الأصلية",
    "Inscrit le": "تاريخ التسجيل",
    "Parents liés :": "أولياء الأمور المرتبطون:",
    "Écrire à la famille sur WhatsApp": "مراسلة الأسرة عبر واتساب",
    "Statut du dossier (automatique) :": "حالة الملف (تلقائية):",
    "Il manque :": "ينقص:",
    "date de naissance": "تاريخ الميلاد",
    "· genre": "· الجنس",
    "· au moins un parent lié": "· ولي أمر مرتبط واحد على الأقل",
    "· téléphone de contact": "· هاتف للتواصل",
    "Parents (": "أولياء الأمور (",
    "Retirer": "إزالة",
    "Ajouter un parent": "إضافة ولي أمر",
    "Lier": "ربط",
    "Aucun autre compte parent actif disponible pour l'instant.": "لا يوجد حاليًا حساب ولي أمر نشط آخر.",
    "Maximum de": "الحد الأقصى",
    "parents atteint — retire un parent avant d'en ajouter un autre.": "أولياء أمور، أزيلوا وليًا قبل إضافة آخر.",
    "Voir le bulletin": "عرض كشف الدرجات",
    "Moyenne générale (": "المعدل العام (",
    "(seuil :": "(العتبة:",
    "Aucune note enregistrée cette année — admission indéterminable.": "لا توجد درجات مسجلة هذه السنة، ولا يمكن تحديد الانتقال.",
    "Évaluer et faire passer en": "التقييم والنقل إلى",
    "Aucune classe supérieure définie après": "لم يُحدَّد قسم أعلى بعد",
    "Historique scolaire": "المسار الدراسي",
    "Aucun historique.": "لا يوجد سجل.",
    "Importer des élèves": "استيراد التلاميذ",
    "Importer des élèves depuis Excel": "استيراد التلاميذ من Excel",
    "Rien n'a été importé.": "لم يتم استيراد أي شيء.",
    "Corrige le fichier puis renvoie-le :": "صحّحوا الملف ثم أعيدوا إرساله:",
    "… et": "… و",
    "autre(s) erreur(s).": "أخطاء أخرى.",
    "Télécharger le modèle Excel": "تنزيل نموذج Excel",
    "Fichier Excel (.xlsx)": "ملف Excel (.xlsx)",
    "Crée d'abord les classes de l'année : l'import range chaque élève dans sa classe.": "أنشئوا أولًا أقسام السنة: الاستيراد يضع كل تلميذ في قسمه.",
    "Importer depuis Excel": "استيراد من Excel",
    "Passage de classe": "الانتقال إلى القسم الأعلى",
    "élèves": "تلاميذ",
    "élève": "تلميذ",
    "Exporter": "تصدير",
    "Exporter :": "تصدير:",
    "cette classe": "هذا القسم",
    "toutes les classes": "كل الأقسام",
    "Dossier": "الملف",
    "Aucun élève ne correspond.": "لا يوجد تلميذ مطابق.",
    "Modifier —": "تعديل —",
    "Modifier le dossier —": "تعديل الملف —",
    "Non précisé": "غير محدد",
    "Inscrire l'élève": "تسجيل التلميذ",
    "Aucune classe n'existe encore.": "لا يوجد أي قسم بعد.",
    "Créer une classe": "إنشاء قسم",
    "avant d'inscrire un élève.": "قبل تسجيل تلميذ.",
    "Préparer le passage": "تحضير الانتقال",
    "Aucune année scolaire postérieure à": "لا توجد سنة دراسية بعد",
    "n'existe encore.": "حتى الآن.",
    "Démarrer la nouvelle année scolaire": "بدء السنة الدراسية الجديدة",
    ", puis reviens ici.": "، ثم عودوا إلى هنا.",
    "Année d'arrivée :": "سنة الوصول:",
    "· Admis →": "· الناجحون ←",
    "· Redoublants →": "· المعيدون ←",
    "Moyenne annuelle /": "المعدل السنوي /",
    "Appliquer le passage": "تطبيق الانتقال",
    "Aucune classe ne contient d'élèves.": "لا يحتوي أي قسم على تلاميذ.",
    "Tous les élèves de cette classe ont déjà été traités.": "تمت معالجة جميع تلاميذ هذا القسم.",

    # Emplois du temps, enseignants
    "Emploi du temps —": "جدول الحصص —",
    "Emploi du temps": "جدول الحصص",
    "Télécharger en PDF": "تنزيل بصيغة PDF",
    "Heure": "الساعة",
    "Ajouter un créneau": "إضافة حصة",
    "Non assigné": "غير مُسنَد",
    "Heure de début": "ساعة البداية",
    "Heure de fin": "ساعة النهاية",
    "Aucun créneau enregistré pour cette classe.": "لا توجد حصص مسجلة لهذا القسم.",
    "Voir mon emploi du temps dans cette classe": "عرض جدول حصصي في هذا القسم",
    "Aucun profil enseignant associé à votre compte pour l'instant — contactez la direction.": "لا يوجد ملف مدرّس مرتبط بحسابكم حاليًا، يرجى الاتصال بالإدارة.",
    "Aucune classe ne t'est encore attribuée.": "لم يُسنَد إليكم أي قسم بعد.",
    "Spécialité :": "التخصص:",
    "Classes affectées": "الأقسام المسندة",
    "Suivi": "المتابعة",
    "Affecter une classe": "إسناد قسم",
    "Affecter": "إسناد",
    "Aucune classe affectée pour l'instant.": "لا توجد أقسام مسندة حاليًا.",
    "Créer un profil enseignant": "إنشاء ملف مدرّس",
    "classe(s)": "قسم",
    "Aucun profil enseignant pour l'instant.": "لا توجد ملفات مدرّسين حاليًا.",
    "Nouveau profil enseignant": "ملف مدرّس جديد",
    "Compte enseignant (déjà approuvé)": "حساب مدرّس (تمت الموافقة عليه)",
    "Choisir un compte": "اختيار حساب",
    "Spécialité / matière principale": "التخصص / المادة الرئيسية",
    "Créer le profil": "إنشاء الملف",
    "Aucun compte enseignant approuvé sans profil pour l'instant. Un enseignant doit d'abord s'inscrire et être validé par le secrétariat.": "لا يوجد حاليًا حساب مدرّس موافق عليه بدون ملف. يجب على المدرّس أولًا التسجيل ثم موافقة الأمانة.",
    "Nouveau profil": "ملف جديد",

    # Finances
    "Finances —": "المالية —",
    "Total dû :": "المجموع المستحق:",
    "Total payé :": "المجموع المدفوع:",
    "Solde :": "الرصيد:",
    "Statut :": "الحالة:",
    "Relancer la famille": "تذكير الأسرة",
    "Sur WhatsApp, gratuitement : le message avec le montant dû est déjà rédigé.": "عبر واتساب مجانًا: الرسالة التي تتضمن المبلغ المستحق جاهزة.",
    "Envoyer aussi par email": "الإرسال أيضًا بالبريد الإلكتروني",
    "En retard :": "متأخر:",
    "(date limite dépassée)": "(تجاوز آخر أجل)",
    "Remise de": "تخفيض بنسبة",
    "sur la scolarité": "على الرسوم الدراسية",
    "Détail par échéance": "التفاصيل حسب القسط",
    "· en retard": "· متأخر",
    "Remise sur la scolarité (%)": "التخفيض على الرسوم الدراسية (%)",
    "Enregistrer la remise": "حفظ التخفيض",
    "Nouveau paiement": "دفعة جديدة",
    "— reste": "— الباقي",
    "Historique des paiements": "سجل الدفعات",
    "N° reçu": "رقم الوصل",
    "Supprimer ce paiement et sa ligne de Caisse associée ?": "حذف هذه الدفعة وسطر الصندوق المرتبط بها؟",
    "Aucun paiement enregistré.": "لا توجد دفعات مسجلة.",
    "Supprimer ce frais ?": "حذف هذه الرسوم؟",
    "Nouveau frais": "رسوم جديدة",
    "Aucun frais annexe pour cette année.": "لا توجد رسوم إضافية لهذه السنة.",
    "Nom ou matricule": "الاسم أو رقم التسجيل",
    "Nom ou matricule de l'élève": "اسم التلميذ أو رقم تسجيله",
    "Aucun élève en retard de paiement.": "لا يوجد تلميذ متأخر في الدفع.",
    "Corriger un paiement": "تصحيح دفعة",
    "Corriger le paiement": "تصحيح الدفعة",
    "Élève :": "التلميذ:",

    # Guides, accueil, profil, recherche
    "Guide —": "الدليل —",
    "À savoir": "معلومات مهمة",
    "← Tous les guides": "→ كل الأدلة",
    "Guides": "الأدلة",
    "Aucun enfant n'est encore rattaché à ton compte. Contacte le secrétariat.": "لم يُربط أي طفل بحسابكم بعد. يرجى الاتصال بالأمانة.",
    "Aucun dossier élève n'est encore rattaché à ton compte. Contacte le secrétariat.": "لم يُربط أي ملف تلميذ بحسابكم بعد. يرجى الاتصال بالأمانة.",
    "Mot de passe actuel": "كلمة المرور الحالية",
    "Nouveau mot de passe": "كلمة المرور الجديدة",
    "Confirmer le nouveau mot de passe": "تأكيد كلمة المرور الجديدة",
    "Changer le mot de passe": "تغيير كلمة المرور",
    "Mes numéros": "أرقامي",
    "Supprimer ce numéro ?": "حذف هذا الرقم؟",
    "Ajouter un numéro": "إضافة رقم",
    "Numéro": "الرقم",
    "Opérateur": "المشغّل",
    "Aucun numéro enregistré pour l'instant.": "لا توجد أرقام مسجلة حاليًا.",
    "Recherche": "البحث",
    "Nom, matricule ou email": "الاسم أو رقم التسجيل أو البريد الإلكتروني",
    "Élèves (": "التلاميذ (",
    "Enseignants (": "المدرّسون (",
    "Comptes (": "الحسابات (",
    "Comptes": "الحسابات",
    "Aucun résultat pour « ": "لا توجد نتائج لـ « ",

    # Notes et bulletins
    "Bulletin —": "كشف الدرجات —",
    "Bulletin — ": "كشف الدرجات — ",
    "Moyenne générale": "المعدل العام",
    "Moyenne de la classe": "معدل القسم",
    "Moyenne /": "المعدل /",
    "Min – Max": "الأدنى – الأعلى",
    "Absences :": "الغيابات:",
    "non justifiée(s),": "غير مبررة،",
    "justifiée(s).": "مبررة.",
    "Appréciation du conseil de classe": "ملاحظة مجلس القسم",
    "Appréciation du conseil de classe :": "ملاحظة مجلس القسم:",
    "Enregistrer l'appréciation": "حفظ الملاحظة",
    "Télécharger le bulletin (PDF)": "تنزيل كشف الدرجات (PDF)",
    "Aucune note enregistrée pour cette période.": "لا توجد درجات مسجلة لهذه الفترة.",
    "Bulletins —": "كشوف الدرجات —",
    "Bulletins — ": "كشوف الدرجات — ",
    "Bulletins": "كشوف الدرجات",
    "Coefficients des matières": "معاملات المواد",
    "Télécharger tous les bulletins (PDF)": "تنزيل كل كشوف الدرجات (PDF)",
    "Plus forte moyenne": "أعلى معدل",
    "Plus faible moyenne": "أدنى معدل",
    "Coefficients —": "المعاملات —",
    "Aucune matière n'est encore affectée à cette classe.": "لم تُسند أي مادة إلى هذا القسم بعد.",
    "Note (/": "الدرجة (/",
    "Enregistrer les notes": "حفظ الدرجات",
    "Supprimer cette évaluation et toutes ses notes ?": "حذف هذا التقييم وكل درجاته؟",
    "Supprimer l'évaluation": "حذف التقييم",
    "Aucun élève dans cette classe.": "لا يوجد تلاميذ في هذا القسم.",
    "Aucune classe à afficher.": "لا توجد أقسام لعرضها.",
    "Notes —": "الدرجات —",
    "Notes — ": "الدرجات — ",
    "Évaluation": "التقييم",
    "Saisir les notes": "إدخال الدرجات",
    "Nouvelle évaluation": "تقييم جديد",
    "Créer et saisir les notes": "الإنشاء وإدخال الدرجات",
    "Aucune évaluation pour l'instant.": "لا توجد تقييمات حاليًا.",
    "Vous n'enseignez pas dans cette classe.": "أنتم لا تدرّسون في هذا القسم.",

    # Plateforme
    "Identité": "الهوية",
    "Nom officiel": "الاسم الرسمي",
    "Sigle": "الاختصار",
    "Devise": "شعار المؤسسة (العبارة)",
    "Préfixe des matricules": "بادئة أرقام التسجيل",
    "Logo": "الشعار",
    "Filigrane des documents": "العلامة المائية للوثائق",
    "Premier compte fondateur": "أول حساب مؤسس",
    "Mot de passe provisoire": "كلمة مرور مؤقتة",
    "Établissements de la plateforme": "مؤسسات المنصة",
    "Nouvel établissement": "مؤسسة جديدة",
    "en cours": "جارية",
    "Entrer": "دخول",
    "Aucun établissement pour l'instant.": "لا توجد مؤسسات حاليًا.",
    "Restaurer": "استعادة",
    "Restaurer «": "استعادة «",
    "Restaurer ": "استعادة ",
    "Les données actuelles de cet établissement seront remplacées": "ستُستبدل البيانات الحالية لهذه المؤسسة",
    "par celles de la sauvegarde : comptes, élèves, notes, paiements, caisse, salaires, bibliothèque.": "ببيانات النسخة الاحتياطية: الحسابات، التلاميذ، الدرجات، الدفعات، الصندوق، الرواتب، المكتبة.",
    "Fichier de sauvegarde (.zip)": "ملف النسخة الاحتياطية (.zip)",
    "Pour confirmer, retape «": "للتأكيد، أعيدوا كتابة «",

    # Salaires
    "Nouveau salaire": "راتب جديد",
    "Total payé": "المجموع المدفوع",
    "Total impayé": "المجموع غير المدفوع",
    "Nom du bénéficiaire": "اسم المستفيد",
    "Payé à partir du": "مدفوع ابتداءً من",
    "Jusqu'au": "إلى غاية",
    "Télécharger cette liste (avec les mêmes filtres) :": "تنزيل هذه القائمة (بنفس عوامل التصفية):",
    "Bénéficiaire": "المستفيد",
    "Fonction": "الوظيفة",
    "Date paiement": "تاريخ الدفع",
    "Marquer payé": "تسجيل كمدفوع",
    "Supprimer cette ligne de salaire ?": "حذف سطر الراتب هذا؟",
    "Salaires du personnel": "رواتب الموظفين",
    "Aucun salaire ne correspond à ces critères.": "لا يوجد راتب مطابق لهذه المعايير.",
    "Somme à percevoir — un billet à la fois": "المبلغ المستحق، ورقة نقدية تلو الأخرى",
    "+ Ajouter un billet": "+ إضافة ورقة نقدية",
    "Email de contact (pour l'avis de paiement)": "بريد التواصل (لإشعار الدفع)",
    "Téléphone de contact": "هاتف التواصل",
    "Enregistrer (impayé)": "حفظ (غير مدفوع)",

    # Secrétariat, statistiques, suivi, tests
    "Demandes de compte": "طلبات الحسابات",
    "Approuver": "موافقة",
    "Refuser": "رفض",
    "Aucune demande en attente.": "لا توجد طلبات في الانتظار.",
    "Demandes": "الطلبات",
    "Statistique globale": "إحصائية عامة",
    "Réussite par sexe": "النجاح حسب الجنس",
    "Indicateur": "المؤشر",
    "Taux de réussite": "نسبة النجاح",
    "Taux d'échec": "نسبة الرسوب",
    "Aucun élève n'a encore de notes saisies pour cette sélection.": "لا يوجد تلميذ له درجات مدخلة لهذا الاختيار بعد.",
    "Total à recouvrer": "المجموع المطلوب تحصيله",
    "Total encaissé": "المجموع المحصَّل",
    "Solde à recouvrer": "الباقي للتحصيل",
    "Taux de recouvrement": "نسبة التحصيل",
    "Par échéance": "حسب القسط",
    "Listes par situation de paiement": "القوائم حسب وضعية الدفع",
    "Situation": "الوضعية",
    "Nb élèves": "عدد التلاميذ",
    "Statistiques — ": "الإحصائيات — ",
    "Suivi des cours —": "متابعة الدروس —",
    "Chapitre": "الدرس",
    "Progression (%)": "التقدّم (%)",
    "En retard sur le programme": "متأخر عن البرنامج",
    "Difficultés rencontrées": "الصعوبات المواجهة",
    "Aucun suivi pour cette classe pour l'instant.": "لا توجد متابعة لهذا القسم حاليًا.",
    "Aucun suivi enregistré pour l'instant.": "لا توجد متابعة مسجلة حاليًا.",
    "Nouveau test": "اختبار جديد",
    "Candidat": "المترشح",
    "Classe demandée": "القسم المطلوب",
    "Date du test": "تاريخ الاختبار",
    "Inscrit —": "مسجَّل —",
    "Aucun test de niveau enregistré.": "لا توجد اختبارات مستوى مسجلة.",
    "Nouveau test de niveau": "اختبار مستوى جديد",
    "Nom du candidat": "اسم المترشح",
    "Téléphone du parent": "هاتف ولي الأمر",
    "— note sur": "— الدرجة من",
    "Et {n} autre(s) classe(s) mieux recouvrée(s).": "و{n} أقسام أخرى نسبة تحصيلها أفضل.",

    # Valeurs calculées (statuts, périodes, libellés)
    "PAYÉ": "مدفوع",
    "IMPAYÉ": "غير مدفوع",
    "PARTIEL": "مدفوع جزئيًا",
    "complet": "مكتمل",
    "incomplet": "غير مكتمل",
    "Aucun": "لا أحد",
    "1er trimestre": "الفصل الأول",
    "2e trimestre": "الفصل الثاني",
    "3e trimestre": "الفصل الثالث",
    "Oui": "نعم",
    "Non": "لا",
    "cette sélection": "هذا الاختيار",
    "tout": "الكل",
    "Verrouiller (sur place)": "قفل (للاطلاع في عين المكان)",
    "Verrouiller": "قفل",
    "Déverrouiller": "فتح القفل",
    "Envoyé": "تم الإرسال",
    "Échec": "فشل",
    "Remplacer la photo": "تغيير الصورة",
    "Photo d'identité": "صورة شمسية",
    "Admissible": "ناجح",
    "Sous le seuil requis": "دون العتبة المطلوبة",
    "Spécialité non précisée": "تخصص غير محدد",
    "Airtel Tchad": "Airtel Tchad",
    "Moov Africa Tchad": "Moov Africa Tchad",
    "Toi": "أنتم",
    "École": "المدرسة",
    "Créer l'établissement": "إنشاء المؤسسة",
    "Actif": "نشط",
    "Suspendu": "معلَّق",
    "Suspendre": "تعليق",
    "Réactiver": "إعادة التفعيل",
    "Scolarité (Finances)": "الرسوم الدراسية (المالية)",
    "frais|Scolarité": "الرسوم الدراسية",
    "Pas de connexion.": "لا يوجد اتصال.",
    "Vous consultez une copie enregistrée sur ce téléphone. Rien ne peut être enregistré avant le retour du réseau.": "تطّلعون على نسخة محفوظة في هذا الهاتف. لا يمكن حفظ أي شيء قبل عودة الشبكة.",
    "Installer l'application": "تثبيت التطبيق",
    "Uniforme": "الزي المدرسي",
    "Fournitures": "اللوازم",
    "Salaire": "راتب",
    "Loyer / Charges": "الإيجار / التكاليف",
    "Transport": "النقل",
    "Entretien": "الصيانة",
    "Divers": "متفرقات",
})

# Jours et mois, pour les dates écrites en toutes lettres.
JOURS = ["الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت", "الأحد"]
MOIS = ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس",
        "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"]


# --- Documents officiels ------------------------------------------------------

DOCUMENTS = {
    # Titres et libellés
    "BULLETIN DE NOTES": "كشف الدرجات",
    "CERTIFICAT DE SCOLARITÉ": "شهادة مدرسية",
    "ATTESTATION DE FRÉQUENTATION": "شهادة مواظبة",
    "Reçu de paiement": "وصل دفع",
    "Nom et prénom(s)": "الاسم واللقب",
    "Classe": "القسم",
    "Matricule": "رقم التسجيل",
    "Genre": "الجنس",
    "Féminin": "أنثى",
    "Masculin": "ذكر",
    "Date de naissance": "تاريخ الميلاد",
    "Effectif": "عدد التلاميذ",
    "Matière": "المادة",
    "Moyenne": "المعدل",
    "Coef.": "المعامل",
    "Points": "النقاط",
    "Rang": "الرتبة",
    "Moy. classe": "معدل القسم",
    "Min – Max": "الأدنى – الأعلى",
    "Appréciation": "التقدير",
    "Total": "المجموع",
    "Période": "الفترة",
    "Moyenne générale": "المعدل العام",
    "Moyenne de la classe": "معدل القسم",
    "Plus forte": "أعلى معدل",
    "Plus faible": "أدنى معدل",
    "Mention": "التقدير",
    "Absences": "الغيابات",
    "non justifiée(s)": "دون مبرر",
    "justifiée(s)": "بمبرر",
    "Décision": "القرار",
    "Appréciation du conseil de classe": "ملاحظات مجلس القسم",
    "Année scolaire": "السنة الدراسية",
    "Référence": "المرجع",
    "Date": "التاريخ",
    "Libellé": "البيان",
    "Élève": "التلميذ",
    "Parent(s)": "الولي",
    "Encaissé par": "استلمه",
    "Montant": "المبلغ",
    "N°": "رقم",

    # Périodes
    "1er trimestre": "الفصل الأول",
    "2e trimestre": "الفصل الثاني",
    "3e trimestre": "الفصل الثالث",
    "Année": "الحصيلة السنوية",

    # Mentions et décisions
    "Excellent": "ممتاز",
    "Très bien": "جيد جدًا",
    "Bien": "جيد",
    "Assez bien": "مستحسن",
    "Passable": "مقبول",
    "Insuffisant": "ضعيف",
    "Admis en classe supérieure": "ينتقل إلى القسم الأعلى",
    "Redouble": "يعيد السنة",

    # Titres du signataire
    "Directeur": "المدير",
    "Directrice": "المديرة",
    "Directeur général": "المدير العام",
    "Directrice générale": "المديرة العامة",
    "Fondateur": "المؤسس",
    "Fondatrice": "المؤسسة",
    "Proviseur": "مدير الثانوية",
    "Censeur": "المراقب العام",
    "Principal": "مدير الإعدادية",
    "Comptable": "المحاسب",
    "Secrétaire": "الكاتب",

    # Pays
    "Tchad": "تشاد",
    "TCHAD": "تشاد",

    # Matières courantes
    "Mathématiques": "الرياضيات",
    "Maths": "الرياضيات",
    "Français": "اللغة الفرنسية",
    "Arabe": "اللغة العربية",
    "Anglais": "اللغة الإنجليزية",
    "Histoire-Géographie": "التاريخ والجغرافيا",
    "Histoire": "التاريخ",
    "Géographie": "الجغرافيا",
    "SVT": "علوم الحياة والأرض",
    "Sciences de la vie et de la terre": "علوم الحياة والأرض",
    "Physique-Chimie": "الفيزياء والكيمياء",
    "Sciences physiques": "العلوم الفيزيائية",
    "Sciences": "العلوم",
    "Éducation civique": "التربية المدنية",
    "Éducation civique et morale": "التربية المدنية والأخلاقية",
    "ECM": "التربية المدنية والأخلاقية",
    "EPS": "التربية البدنية",
    "Éducation physique et sportive": "التربية البدنية والرياضية",
    "Éducation islamique": "التربية الإسلامية",
    "Instruction religieuse": "التربية الدينية",
    "Informatique": "الإعلام الآلي",
    "Philosophie": "الفلسفة",
    "Dessin": "الرسم",
    "Musique": "الموسيقى",
    "Lecture": "القراءة",
    "Écriture": "الكتابة",
    "Calcul": "الحساب",
    "Dictée": "الإملاء",
    "Rédaction": "التعبير الكتابي",
    "Grammaire": "القواعد",
    "Conjugaison": "التصريف",
    "Orthographe": "الإملاء",
    "Vocabulaire": "المفردات",
    "Coran": "القرآن الكريم",
}


# --- Messages ajoutés par l'audit de sécurité (oct. 2026) --------------------
INTERFACE.update({
    "Requête invalide": "طلب غير صالح",
    "La demande envoyée n'a pas pu être traitée.": "تعذّرت معالجة الطلب المرسَل.",
    "La page a expiré. Recharge-la, puis recommence.": "انتهت صلاحية الصفحة. أعد تحميلها ثم أعد المحاولة.",
    "Une valeur envoyée est invalide.": "إحدى القيم المرسلة غير صالحة.",
    "L'email de vérification n'a pas pu partir. Utilise « Renvoyer le code » dans quelques minutes.":
        "تعذّر إرسال بريد التحقق. استخدم « إعادة إرسال الرمز » بعد بضع دقائق.",
    "L'email n'a pas pu partir. Réessaie dans quelques minutes ou contacte l'école.":
        "تعذّر إرسال البريد. أعد المحاولة بعد بضع دقائق أو اتصل بالمدرسة.",
    "Si un compte existe avec cet identifiant, un lien de réinitialisation a été envoyé "
    "(au parent pour un compte élève). Sans email, adresse-toi au secrétariat.":
        "إذا كان هناك حساب بهذا المعرّف، فقد أُرسل رابط لإعادة تعيين كلمة المرور "
        "(إلى وليّ الأمر بالنسبة لحساب التلميذ). في حال عدم وجود بريد إلكتروني، توجّه إلى الأمانة.",
    "Le mot de passe doit faire au moins 8 caractères.": "يجب أن تتكوّن كلمة المرور من 8 أحرف على الأقل.",
    "Relance envoyée.": "تم إرسال التذكير.",
})


# --- Vie scolaire : cahier de textes, discipline, calendrier, départ (oct. 2026)
INTERFACE.update({
    # Cahier de textes et devoirs
    "Cahier de textes": "دفتر النصوص",
    "Ouvrir le cahier": "فتح الدفتر",
    "Ce qui a été fait en classe et le travail à faire.": "ما أُنجز في القسم والواجبات المطلوبة.",
    "Nouvelle séance": "حصة جديدة",
    "Date de la séance": "تاريخ الحصة",
    "Ce qui a été fait": "ما تم إنجازه",
    "Travail à faire (facultatif)": "الواجب المطلوب (اختياري)",
    "Travail à faire": "الواجب المطلوب",
    "Pour le": "ليوم",
    "pour le": "ليوم",
    "Séances": "الحصص",
    "À faire": "المطلوب",
    "Retirer cette séance du cahier ?": "حذف هذه الحصة من الدفتر؟",
    "Le cahier de textes de cette classe est encore vide.": "دفتر النصوص لهذا القسم فارغ حتى الآن.",
    "Devoirs": "الواجبات",
    "Mes devoirs": "واجباتي",
    "Devoirs et cahier de textes": "الواجبات ودفتر النصوص",
    "Dernières séances": "آخر الحصص",
    "Aucun devoir à rendre pour l'instant.": "لا توجد واجبات مطلوبة حاليًا.",
    "Choisis une de tes matières et décris la séance.": "اختر إحدى موادك وصِف الحصة.",
    "La date de remise du devoir ne peut pas précéder la séance.": "لا يمكن أن يسبق تاريخ تسليم الواجب تاريخ الحصة.",
    "Séance ajoutée au cahier de textes.": "أُضيفت الحصة إلى دفتر النصوص.",
    "Séance retirée du cahier de textes.": "حُذفت الحصة من دفتر النصوص.",
    # Retards et discipline
    "Retards et discipline": "التأخرات والانضباط",
    "Retards, avertissements, blâmes, convocations et exclusions.": "التأخرات والإنذارات والتوبيخات والاستدعاءات والإقصاءات.",
    "Signaler un retard ou un incident": "تسجيل تأخر أو مخالفة",
    "Minutes de retard": "دقائق التأخر",
    "Durée de l'exclusion (jours)": "مدة الإقصاء (بالأيام)",
    "Les parents sont prévenus par email de toute mesure de discipline, et au troisième retard du mois.":
        "يُبلَّغ أولياء الأمور بالبريد الإلكتروني بكل إجراء تأديبي، وعند التأخر الثالث في الشهر.",
    "Aucun élève dans tes classes.": "لا يوجد تلاميذ في أقسامك.",
    "j": "ي",
    "Retirer cette ligne du registre ?": "حذف هذا السطر من السجل؟",
    "Aucun retard ni incident enregistré.": "لم يُسجَّل أي تأخر أو مخالفة.",
    "Choisis l'élève et le type.": "اختر التلميذ والنوع.",
    "Précise le motif.": "حدّد السبب.",
    "Enregistré dans le registre de discipline.": "سُجّل في سجل الانضباط.",
    "Ligne retirée du registre.": "حُذف السطر من السجل.",
    "Absences et discipline": "الغيابات والانضباط",
    "Mes absences": "غياباتي",
    "Retards :": "التأخرات :",
    "Retard": "تأخر",
    "Avertissement": "إنذار",
    "Blâme": "توبيخ",
    "Convocation des parents": "استدعاء أولياء الأمور",
    "Exclusion temporaire": "إقصاء مؤقت",
    "Autre": "أخرى",
    # Calendrier scolaire
    "Calendrier scolaire": "الرزنامة المدرسية",
    "Rentrée, vacances, jours fériés, compositions et réunions.": "الدخول المدرسي والعطل والأعياد والامتحانات والاجتماعات.",
    "Ajouter une date": "إضافة موعد",
    "Modifier une date": "تعديل موعد",
    "Du": "من",
    "Au (facultatif)": "إلى (اختياري)",
    "du": "من",
    "au": "إلى",
    "Précisions": "تفاصيل",
    "Réservé au personnel (invisible pour les familles)": "خاص بالموظفين (لا يظهر للأسر)",
    "Interne": "داخلي",
    "Dates passées de l'année": "مواعيد السنة الماضية",
    "Retirer cette date du calendrier ?": "حذف هذا الموعد من الرزنامة؟",
    "Aucune date à venir dans le calendrier.": "لا توجد مواعيد قادمة في الرزنامة.",
    "Prochainement": "قريبًا",
    "Date ajoutée au calendrier.": "أُضيف الموعد إلى الرزنامة.",
    "Calendrier mis à jour.": "حُدّثت الرزنامة.",
    "Date retirée du calendrier.": "حُذف الموعد من الرزنامة.",
    "Indique le titre, le type et la date de début.": "أدخل العنوان والنوع وتاريخ البداية.",
    "La date de fin ne peut pas précéder la date de début.": "لا يمكن أن يسبق تاريخ النهاية تاريخ البداية.",
    "Rentrée": "الدخول المدرسي",
    "Vacances": "عطلة",
    "Jour férié": "يوم عطلة رسمية",
    "Compositions et examens": "الفروض والامتحانات",
    "Réunion": "اجتماع",
    "Événement": "حدث",
    # Départ d'un élève
    "Élève parti de l'école": "تلميذ غادر المدرسة",
    "le": "يوم",
    "vers": "نحو",
    "Certificat de radiation (PDF)": "شهادة شطب (PDF)",
    "Certificat de radiation": "شهادة شطب",
    "Réintégrer en": "إعادة الإدماج في",
    "Réintégrer l'élève": "إعادة إدماج التلميذ",
    "Pour le réintégrer, crée d'abord les classes de l'année en cours.": "لإعادة إدماجه، أنشئ أولًا أقسام السنة الجارية.",
    "Départ de l'élève (radiation)": "مغادرة التلميذ (الشطب)",
    "L'élève quitte les listes de classe ; son dossier, ses notes et ses paiements sont conservés. Il peut être réintégré.":
        "يُحذف التلميذ من قوائم القسم، مع الاحتفاظ بملفه ونقاطه ومدفوعاته. ويمكن إعادة إدماجه.",
    "Date du départ": "تاريخ المغادرة",
    "École d'accueil (en cas de transfert)": "المدرسة المستقبِلة (في حالة الانتقال)",
    "Enregistrer le départ": "تسجيل المغادرة",
    "Enregistrer le départ de cet élève ?": "تسجيل مغادرة هذا التلميذ؟",
    "Anciens élèves": "التلاميذ القدامى",
    "Élèves partis : transfert, abandon, fin de scolarité…": "التلاميذ المغادرون : انتقال، انقطاع، نهاية الدراسة…",
    "Dernière classe": "آخر قسم",
    "Départ": "المغادرة",
    "Aucun ancien élève.": "لا يوجد تلاميذ قدامى.",
    "Choisis le motif du départ.": "اختر سبب المغادرة.",
    "Départ enregistré. Le dossier reste dans « Anciens élèves ».": "سُجّلت المغادرة. يبقى الملف ضمن « التلاميذ القدامى ».",
    "Choisis une classe de l'année en cours.": "اختر قسمًا من السنة الجارية.",
    "Élève réintégré.": "أُعيد إدماج التلميذ.",
    "Transfert vers une autre école": "انتقال إلى مدرسة أخرى",
    "Abandon": "انقطاع عن الدراسة",
    "Déménagement de la famille": "انتقال الأسرة",
    "Exclusion définitive": "طرد نهائي",
    "Fin de scolarité": "نهاية الدراسة",
    "Sortant (fin d'année)": "مغادر (نهاية السنة)",
})


# --- Réglages par école : permissions, connexion, couleurs, paie (oct. 2026)
INTERFACE.update({
    "Réglage propre à l'école :": "إعداد خاص بالمدرسة :",
    "Cette école a ses propres réglages.": "لهذه المدرسة إعداداتها الخاصة.",
    "Cette école suit le réglage commun à toutes les écoles.": "تتبع هذه المدرسة الإعداد المشترك بين كل المدارس.",
    "Seules les cases qui diffèrent du réglage commun sont retenues pour l'école ; le reste suit le réglage commun.":
        "لا تُحفظ للمدرسة إلا الخانات المختلفة عن الإعداد المشترك، والباقي يتبع الإعداد المشترك.",
    "Réglage commun à toutes les écoles : il s'applique partout où une école n'a rien décidé elle-même.":
        "الإعداد المشترك بين كل المدارس : يُطبَّق حيثما لم تقرر المدرسة شيئًا بنفسها.",
    "Voir le réglage commun à toutes les écoles": "عرض الإعداد المشترك بين كل المدارس",
    "Voir le réglage de l'école en cours": "عرض إعداد المدرسة الحالية",
    "Les zones techniques (rôles, journaux, sauvegarde) se règlent avec le développeur de la plateforme.":
        "تُضبط المناطق التقنية (الأدوار، السجلات، النسخ الاحتياطي) مع مطوّر المنصة.",
    "Revenir au réglage commun": "العودة إلى الإعداد المشترك",
    "Effacer les réglages propres à cette école ?": "حذف الإعدادات الخاصة بهذه المدرسة؟",
    "L'école suit de nouveau le réglage commun.": "عادت المدرسة إلى اتباع الإعداد المشترك.",
    "Couleurs de l'interface": "ألوان الواجهة",
    "Le menu, les en-têtes et les boutons prennent les couleurs de l'école. Une couleur trop claire est refusée : le texte blanc doit rester lisible.":
        "تأخذ القائمة والعناوين والأزرار ألوان المدرسة. يُرفض اللون الفاتح جدًا : يجب أن يبقى النص الأبيض مقروءًا.",
    "Couleur principale": "اللون الرئيسي",
    "Couleur d'accent": "لون التمييز",
    "Garder les couleurs de la plateforme": "الإبقاء على ألوان المنصة",
    "Couleur principale : format attendu #RRVVBB.": "اللون الرئيسي : الصيغة المطلوبة #RRVVBB.",
    "Couleur d'accent : format attendu #RRVVBB.": "لون التمييز : الصيغة المطلوبة #RRVVBB.",
    "Couleur principale trop claire : le texte blanc serait illisible. Choisis une teinte plus foncée.":
        "اللون الرئيسي فاتح جدًا : سيصبح النص الأبيض غير مقروء. اختر درجة أغمق.",
    "Couleur d'accent trop claire : le texte blanc serait illisible. Choisis une teinte plus foncée.":
        "لون التمييز فاتح جدًا : سيصبح النص الأبيض غير مقروء. اختر درجة أغمق.",
    "Sécurité des connexions": "أمان تسجيل الدخول",
    "Code par email à chaque connexion de la direction et de la comptabilité": "رمز عبر البريد الإلكتروني عند كل دخول للإدارة والمحاسبة",
    "Avant d'activer : vérifie que les emails partent bien (journal des emails) et que chaque membre de la direction a une adresse email qu'il consulte. Un appareil peut être marqué « de confiance » pendant 30 jours.":
        "قبل التفعيل : تأكد من أن الرسائل تُرسل فعلًا (سجل البريد) وأن لكل عضو في الإدارة بريدًا يطّلع عليه. يمكن اعتبار جهاز « موثوقًا » لمدة 30 يومًا.",
    "Code de connexion": "رمز الدخول",
    "Pour protéger les comptes de la direction, un code à 6 chiffres vient d'être envoyé à":
        "لحماية حسابات الإدارة، أُرسل للتو رمز من 6 أرقام إلى",
    "Code reçu par email": "الرمز المستلم عبر البريد",
    "Faire confiance à cet appareil pendant 30 jours": "الوثوق بهذا الجهاز لمدة 30 يومًا",
    "À ne cocher que sur ton propre téléphone ou ordinateur, jamais sur un appareil partagé.":
        "لا تحدد هذا الخيار إلا على هاتفك أو حاسوبك الخاص، وليس على جهاز مشترك أبدًا.",
    "Le code de connexion n'a pas pu partir par email. Réessaie dans quelques minutes.":
        "تعذّر إرسال رمز الدخول عبر البريد. أعد المحاولة بعد بضع دقائق.",
    "Trop de codes faux. Reconnecte-toi pour recevoir un nouveau code.": "رموز خاطئة كثيرة. سجّل الدخول من جديد لتلقي رمز جديد.",
    "Code invalide ou expiré.": "الرمز غير صالح أو منتهي الصلاحية.",
    "Nouveau code envoyé.": "أُرسل رمز جديد.",
    "Retour à la connexion": "العودة إلى تسجيل الدخول",
    "Fiche de paie (PDF)": "كشف الراتب (PDF)",
    "Mes fiches de paie": "كشوف رواتبي",
    "Net à payer": "صافي الأجر",
    "Aucun salaire enregistré à ton nom.": "لا يوجد راتب مسجل باسمك.",
    "Primes et retenues (facultatif)": "العلاوات والاقتطاعات (اختياري)",
    "Primes et indemnités": "العلاوات والتعويضات",
    "Motif des primes": "سبب العلاوات",
    "Retenues (avance, absences…)": "الاقتطاعات (تسبيق، غيابات…)",
    "Motif des retenues": "سبب الاقتطاعات",
    "Net à payer = somme ci-dessus + primes − retenues. La fiche de paie détaille chaque ligne.":
        "صافي الأجر = المبلغ أعلاه + العلاوات − الاقتطاعات. يفصّل كشف الراتب كل سطر.",
    "Les retenues dépassent le salaire : le net à payer doit rester positif.":
        "الاقتطاعات تتجاوز الراتب : يجب أن يبقى صافي الأجر موجبًا.",
    "Fiche": "الكشف",
})


# --- Noms des rôles et des modules de la matrice des permissions (oct. 2026)
INTERFACE.update({
    "Développeur": "المطوّر",
    "Super-administrateur": "المشرف العام للمنصة",
    "Fondateur": "المؤسس",
    "Administrateur général": "المدير العام",
    "Directeur du primaire": "مدير الابتدائي",
    "Directeur du collège": "مدير الإعدادي",
    "Secrétaire": "الكاتب",
    "Comptable": "المحاسب",
    "Responsable pédagogique": "المسؤول التربوي",
    "Bibliothécaire": "أمين المكتبة",
    "Bulletins (consultation)": "كشوف الدرجات (اطلاع)",
    "Annonces (publication)": "الإعلانات (نشر)",
    "Validation des comptes": "المصادقة على الحسابات",
    "Alertes (absences/moyennes)": "التنبيهات (الغيابات/المعدلات)",
    "Messagerie parent-école": "المراسلة بين الأولياء والمدرسة",
    "Cahier de textes (consultation)": "دفتر النصوص (اطلاع)",
    "Calendrier scolaire (modification)": "الرزنامة المدرسية (تعديل)",
    "Attribution des rôles": "إسناد الأدوار",
    "Sauvegarde des données": "النسخ الاحتياطي للبيانات",
})


# --- Pré-inscription en ligne et prêt de livres (oct. 2026)
INTERFACE.update({
    "Pré-inscription en ligne": "التسجيل المسبق عبر الإنترنت",
    "Choisis l'école où tu souhaites inscrire ton enfant.": "اختر المدرسة التي ترغب في تسجيل طفلك فيها.",
    "Aucune école n'accepte de pré-inscription pour l'instant.": "لا توجد مدرسة تقبل التسجيل المسبق حاليًا.",
    "Remplis ce formulaire : le secrétariat te contactera pour fixer la date du test de niveau. La pré-inscription ne vaut pas inscription.":
        "املأ هذه الاستمارة : ستتصل بك الأمانة لتحديد موعد اختبار المستوى. التسجيل المسبق لا يعني التسجيل النهائي.",
    "L'enfant": "الطفل",
    "Le parent": "وليّ الأمر",
    "Je ne sais pas encore": "لا أعرف بعد",
    "École fréquentée cette année": "المدرسة التي يدرس بها هذه السنة",
    "Téléphone (WhatsApp de préférence)": "الهاتف (واتساب إن أمكن)",
    "Email (facultatif)": "البريد الإلكتروني (اختياري)",
    "Message (facultatif)": "رسالة (اختياري)",
    "Message": "الرسالة",
    "Envoyer la pré-inscription": "إرسال التسجيل المسبق",
    "Pré-inscription": "التسجيل المسبق",
    "Pré-inscriptions": "التسجيلات المسبقة",
    "Pré-inscription envoyée": "تم إرسال التسجيل المسبق",
    "Merci. Le secrétariat de l'école va étudier la demande et te contactera pour le test de niveau.":
        "شكرًا. ستدرس أمانة المدرسة الطلب وتتصل بك من أجل اختبار المستوى.",
    "Référence à garder :": "المرجع الواجب الاحتفاظ به :",
    "Retour à l'accueil": "العودة إلى الصفحة الرئيسية",
    "Vous souhaitez inscrire votre enfant ?": "هل ترغبون في تسجيل طفلكم؟",
    "Faire une pré-inscription en ligne": "القيام بتسجيل مسبق عبر الإنترنت",
    "Reçue le": "تاريخ الاستلام",
    "Test de niveau": "اختبار المستوى",
    "Convoquer au test de niveau": "استدعاء لاختبار المستوى",
    "Classe du test": "قسم الاختبار",
    "Heure (facultatif)": "الساعة (اختياري)",
    "Le test est créé dans « Tests de niveau ». La famille reçoit la convocation par email si elle en a donné un ; sinon, préviens-la sur WhatsApp.":
        "يُنشأ الاختبار في « اختبارات المستوى ». تتلقى الأسرة الاستدعاء بالبريد إن قدمت عنوانًا، وإلا فأبلغها عبر واتساب.",
    "Convoquer": "استدعاء",
    "Crée d'abord les classes de l'année en cours.": "أنشئ أولًا أقسام السنة الجارية.",
    "Refuser la demande": "رفض الطلب",
    "Motif (envoyé à la famille)": "السبب (يُرسل إلى الأسرة)",
    "Adresse à partager avec les familles :": "العنوان الذي يُشارك مع الأسر :",
    "Aucune pré-inscription ici.": "لا توجد تسجيلات مسبقة هنا.",
    "Demandes déposées en ligne par les familles.": "طلبات أودعتها الأسر عبر الإنترنت.",
    "Choisis la classe du test.": "اختر قسم الاختبار.",
    "Candidat convoqué : le test de niveau est créé.": "تم استدعاء المترشح : أُنشئ اختبار المستوى.",
    "Demande refusée.": "رُفض الطلب.",
    "Nouvelle": "جديدة",
    "Convoqué au test": "مستدعى للاختبار",
    "Refusée": "مرفوضة",
    "Indique le nom de l'enfant et celui du parent.": "أدخل اسم الطفل واسم وليّ الأمر.",
    "Numéro de téléphone invalide.": "رقم الهاتف غير صالح.",
    "Adresse email invalide.": "عنوان البريد الإلكتروني غير صالح.",
    "Pré-inscriptions à traiter": "تسجيلات مسبقة في الانتظار",
    "Demandes déposées en ligne par des familles": "طلبات أودعتها أسر عبر الإنترنت",
    # Prêt de livres
    "Livres et prêts": "الكتب والإعارة",
    "Prêt de livres": "إعارة الكتب",
    "Les livres papier de la bibliothèque, prêtés aux élèves et au personnel.": "الكتب الورقية للمكتبة، المُعارة للتلاميذ والموظفين.",
    "Livres prêtés": "الكتب المُعارة",
    "Retards": "التأخرات",
    "Ajouter un livre": "إضافة كتاب",
    "Auteur": "المؤلف",
    "Cote": "الرمز",
    "cote": "الرمز",
    "Cote (numéro sur le livre)": "الرمز (الرقم المكتوب على الكتاب)",
    "Catégorie": "الصنف",
    "Roman, manuel de CM2…": "رواية، كتاب مدرسي للسنة الخامسة…",
    "Nombre d'exemplaires": "عدد النسخ",
    "Disponibles": "المتوفرة",
    "disponible(s)": "متوفرة",
    "Titre, auteur ou cote": "العنوان أو المؤلف أو الرمز",
    "Aucun livre dans le catalogue.": "لا يوجد أي كتاب في الفهرس.",
    "Prêter un exemplaire": "إعارة نسخة",
    "Emprunteur": "المستعير",
    "Date du prêt": "تاريخ الإعارة",
    "À rendre le": "يُعاد يوم",
    "à rendre le": "يُعاد يوم",
    "Remarque (état du livre…)": "ملاحظة (حالة الكتاب…)",
    "Enregistrer le prêt": "تسجيل الإعارة",
    "Prêts": "الإعارات",
    "Prêté le": "أُعير يوم",
    "Rendu le": "أُعيد يوم",
    "Retour": "الإرجاع",
    "Modifier le livre": "تعديل الكتاب",
    "Retirer du catalogue": "حذف من الفهرس",
    "Retirer ce livre du catalogue ?": "حذف هذا الكتاب من الفهرس؟",
    "Ce livre n'a pas encore été prêté.": "لم يُعر هذا الكتاب بعد.",
    "Livre": "الكتاب",
    "Relancer": "تذكير",
    "Aucun livre en retard.": "لا يوجد كتاب متأخر.",
    "Aucun livre prêté en ce moment.": "لا يوجد كتاب مُعار حاليًا.",
    "Livres empruntés": "الكتب المستعارة",
    "Livre ajouté au catalogue.": "أُضيف الكتاب إلى الفهرس.",
    "Livre mis à jour.": "حُدّث الكتاب.",
    "Ce livre a encore des exemplaires prêtés.": "ما زالت لهذا الكتاب نسخ مُعارة.",
    "Livre retiré du catalogue.": "حُذف الكتاب من الفهرس.",
    "Choisis la personne qui emprunte le livre.": "اختر الشخص الذي يستعير الكتاب.",
    "Aucun exemplaire disponible.": "لا توجد نسخة متوفرة.",
    "La date de retour ne peut pas précéder la date du prêt.": "لا يمكن أن يسبق تاريخ الإرجاع تاريخ الإعارة.",
    "Prêt enregistré.": "سُجّلت الإعارة.",
    "Retour enregistré.": "سُجّل الإرجاع.",
    "Rappel envoyé.": "أُرسل التذكير.",
    "Aucune adresse email pour ce rappel, ou l'envoi a échoué.": "لا يوجد عنوان بريد لهذا التذكير، أو فشل الإرسال.",
    "Le titre est obligatoire.": "العنوان إلزامي.",
    "Nombre d'exemplaires invalide.": "عدد النسخ غير صالح.",
    "Il y a plus d'exemplaires prêtés que ce nombre.": "عدد النسخ المُعارة أكبر من هذا العدد.",
    "Livres non rendus": "كتب لم تُعد",
    "Prêts dont la date de retour est passée": "إعارات تجاوزت تاريخ الإرجاع",
})
