"""Traductions arabes (oct. 2026). Clé : le texte français exact tel
qu'il apparaît dans les modèles ; valeur : sa traduction.

Un texte absent de ces listes s'affiche simplement en français. Pour
traduire un nouvel écran : entourer ses textes de _("…") dans le modèle,
puis les ajouter ici. À faire relire par un arabophone de l'école."""

# --- Interface ----------------------------------------------------------------

INTERFACE = {
    # Menu et barre du haut
    "Ouvrir le menu": "فتح القائمة",
    "Tableau de bord": "لوحة القيادة",
    "Plateforme": "المنصة",
    "Fiche": "البطاقة",
    "Scolarité": "التمدرس",
    "Bulletin": "كشف الدرجات",
    "Mon espace": "فضائي",
    "Ma fiche": "بطاقتي",
    "Mon bulletin": "كشف درجاتي",
    "Mon emploi du temps": "جدول حصصي",
    "Classes": "الأقسام",
    "Élèves": "التلاميذ",
    "Tests de niveau": "اختبارات المستوى",
    "Documents officiels": "الوثائق الرسمية",
    "Pédagogie": "الشؤون التربوية",
    "Notes et bulletins": "الدرجات والكشوف",
    "Absences": "الغيابات",
    "Emplois du temps": "جداول الحصص",
    "Enseignants": "المدرسون",
    "Mes classes": "أقسامي",
    "Suivi des cours": "متابعة الدروس",
    "Alertes": "التنبيهات",
    "Finances": "المالية",
    "Caisse": "الصندوق",
    "Salaires": "الرواتب",
    "Statistiques": "الإحصائيات",
    "Messages": "الرسائل",
    "Relances WhatsApp": "التذكيرات عبر واتساب",
    "Annonces": "الإعلانات",
    "Bibliothèque": "المكتبة",
    "Assistant": "المساعد",
    "Administration": "الإدارة",
    "Demandes de comptes": "طلبات الحسابات",
    "Comptes et rôles": "الحسابات والأدوار",
    "Établissement": "المؤسسة",
    "Télécharger une sauvegarde": "تنزيل نسخة احتياطية",
    "Mon profil": "ملفي الشخصي",
    "Déconnexion": "تسجيل الخروج",
    "Propulsé par": "بدعم من",
    "Rechercher un nom…": "البحث عن اسم…",
    "Rechercher un élève, un enseignant ou un compte": "البحث عن تلميذ أو مدرس أو حساب",
    "Connexion": "تسجيل الدخول",
    "Accueil": "الرئيسية",
    "Langue": "اللغة",
    "Afficher en français": "العرض بالفرنسية",
    "Afficher en arabe": "العرض بالعربية",

    # Page publique et connexion
    "Gestion scolaire : inscriptions, notes, finances, emploi du temps et communication.":
        "التسيير المدرسي: التسجيل، الدرجات، المالية، جدول الحصص والتواصل.",
    "Se connecter": "الدخول",
    "Créer un compte": "إنشاء حساب",
    "Vous avez reçu un bulletin, un certificat ou un reçu ?": "استلمتم كشف درجات أو شهادة أو وصلًا؟",
    "Vérifier qu'il est authentique": "تحققوا من صحته",
    "Email ou matricule": "البريد الإلكتروني أو رقم التسجيل",
    "Mot de passe": "كلمة المرور",
    "Mot de passe oublié ?": "نسيتم كلمة المرور؟",
    "Nouveau ici ?": "جديد هنا؟",
    "Afficher ou masquer le mot de passe": "إظهار كلمة المرور أو إخفاؤها",

    # Tableau de bord
    "Bonjour, {prenom}": "مرحبًا، {prenom}",
    "année scolaire {annee}": "السنة الدراسية {annee}",
    "Encaisser un paiement": "تسجيل دفعة",
    "Inscrire un élève": "تسجيل تلميذ",
    "Sauvegarde recommandée.": "يُنصح بأخذ نسخة احتياطية.",
    "Télécharger une sauvegarde maintenant": "تنزيل نسخة احتياطية الآن",
    "Indicateurs clés": "المؤشرات الرئيسية",
    "Encaissé en {mois}": "المحصل في شهر {mois}",
    "sur": "من",
    "à": "على الساعة",
    "Inscription": "التسجيل",
    "Tranche 1 (novembre)": "القسط الأول (نوفمبر)",
    "Tranche 2 (février)": "القسط الثاني (فبراير)",
    "Mes enfants": "أبنائي",
    "Mon EDT": "جدول حصصي",
    "par rapport à l'an dernier": "مقارنة بالسنة الماضية",
    "Depuis le début du mois": "منذ بداية الشهر",
    "Recouvrement de l'année": "نسبة التحصيل السنوية",
    "du total attendu": "من المبلغ المتوقع",
    "Reste": "المتبقي",
    "Élèves inscrits": "التلاميذ المسجلون",
    "{filles} filles · {garcons} garçons · {classes} classes": "{filles} بنات · {garcons} بنين · {classes} أقسام",
    "Absents aujourd'hui": "الغائبون اليوم",
    "dont {n} non justifiés": "منهم {n} دون مبرر",
    "Aucune absence signalée": "لا توجد غيابات مسجلة",
    "Échéancier de la scolarité": "جدول أقساط التمدرس",
    "Voir les retards": "عرض المتأخرات",
    "Montant encaissé par rapport au montant attendu, pour chaque échéance.":
        "المبلغ المحصل مقارنة بالمبلغ المتوقع لكل قسط.",
    "limite le {date}": "آخر أجل {date}",
    "{paye} sur {attendu}": "{paye} من {attendu}",
    "Encaissé": "المحصل",
    "Reste à encaisser": "المتبقي للتحصيل",
    "À traiter": "للمعالجة",
    "Rien en attente. Tout est à jour.": "لا شيء في الانتظار. كل شيء محدث.",
    "Recouvrement par classe": "التحصيل حسب القسم",
    "Toutes les statistiques": "كل الإحصائيات",
    "Part du total dû déjà payée. Les classes les plus en retard en premier.":
        "نسبة المبلغ المستحق المدفوعة. الأقسام الأكثر تأخرًا أولًا.",
    "Classe": "القسم",
    "Taux": "النسبة",
    "Reste dû": "المتبقي",
    "État": "الحالة",
    "Bon": "جيد",
    "À suivre": "للمتابعة",
    "Critique": "حرج",
    "Aucun frais de scolarité n'est encore fixé pour cette année.": "لم تُحدد رسوم التمدرس لهذه السنة بعد.",
    "Absences du jour": "غيابات اليوم",
    "Faire l'appel": "تسجيل الحضور",
    "Aucune absence n'a été signalée aujourd'hui.": "لم يُسجل أي غياب اليوم.",
    "{n} absent(s)": "{n} غائب",
    "sur {n}": "من {n}",
    "Derniers paiements": "آخر الدفعات",
    "Journal de caisse": "سجل الصندوق",
    "Élève": "التلميذ",
    "Objet": "الموضوع",
    "Mode": "طريقة الدفع",
    "Montant": "المبلغ",
    "Reçu": "الوصل",
    "Date": "التاريخ",
    "Aucun paiement enregistré pour le moment.": "لا توجد دفعات مسجلة حاليًا.",
    "Guides d'utilisation": "أدلة الاستخدام",
    "Lire le guide →": "← قراءة الدليل",
    "Espèces": "نقدًا",
    "Mobile Money": "الدفع عبر الهاتف",
    "Virement": "تحويل بنكي",

    # Tâches « À traiter »
    "Familles en retard de paiement": "أسر متأخرة في الدفع",
    "Une échéance dépassée n'est pas soldée": "قسط تجاوز أجله ولم يُسدد",
    "Élèves en alerte": "تلاميذ في وضعية تنبيه",
    "Absences non justifiées répétées": "غيابات متكررة دون مبرر",
    "Parents à prévenir": "أولياء يجب إخطارهم",
    "Absences non justifiées du jour, à signaler sur WhatsApp": "غيابات اليوم دون مبرر، للإبلاغ عنها عبر واتساب",
    "Comptes à valider": "حسابات للمصادقة",
    "Demandes d'inscription en attente": "طلبات تسجيل في الانتظار",
    "Messages de parents": "رسائل الأولياء",
    "Conversations avec un message non lu": "محادثات بها رسالة غير مقروءة",

    # Vérification d'un document
    "Vérifier un document": "التحقق من وثيقة",
    "Document authentique": "وثيقة أصلية",
    "Document annulé par l'école": "وثيقة ألغتها المؤسسة",
    "Ce document a bien été émis, mais l'école l'a annulé depuis. Il n'est plus valable.":
        "صدرت هذه الوثيقة فعلًا، لكن المؤسسة ألغتها لاحقًا. لم تعد صالحة.",
    "Il a été émis par {ecole} le {date}.": "أصدرتها {ecole} بتاريخ {date}.",
    "Comparez avec le papier. Si une seule information diffère, le document a été modifié après son émission.":
        "قارنوا مع النسخة الورقية. إذا اختلفت معلومة واحدة، فقد عُدلت الوثيقة بعد إصدارها.",
    "Date d'émission": "تاريخ الإصدار",
    "Matricule": "رقم التسجيل",
    "Référence": "المرجع",
    "Aucun document ne porte ce code": "لا توجد وثيقة تحمل هذا الرمز",
    "Vérifiez la saisie. Si le code est correct, ce document n'a pas été émis par une école de {plateforme} : il peut s'agir d'un faux.":
        "تحققوا من الرمز المُدخل. إذا كان صحيحًا، فهذه الوثيقة لم تصدرها أي مؤسسة على {plateforme}، وقد تكون مزورة.",
    "Chaque bulletin, certificat, attestation et reçu porte un QR code et un code de 12 caractères. Scannez le QR code avec l'appareil photo de votre téléphone, ou saisissez le code ci-dessous.":
        "يحمل كل كشف درجات وشهادة ووصل رمز QR ورمزًا من 12 حرفًا. امسحوا رمز QR بكاميرا الهاتف، أو أدخلوا الرمز أدناه.",
    "Code du document": "رمز الوثيقة",
    "Vérifier": "تحقق",
    "Ex. K7QF-3M9X-PA2D": "مثال: K7QF-3M9X-PA2D",

    # Relances WhatsApp
    "Le message est déjà rédigé : cliquez sur un parent, WhatsApp s'ouvre, il ne reste qu'à appuyer sur Envoyer.":
        "الرسالة جاهزة: انقروا على اسم الولي، يُفتح واتساب، ولا يبقى سوى الضغط على إرسال.",
    "Absences non justifiées": "غيابات دون مبرر",
    "Jour": "اليوم",
    "Prévenu à {heure}": "تم الإخطار على الساعة {heure}",
    "par {nom}": "من طرف {nom}",
    "À prévenir": "للإخطار",
    "Aucune absence non justifiée ce jour-là.": "لا توجد غيابات دون مبرر في هذا اليوم.",
    "Paiements en retard": "دفعات متأخرة",
    "Soldes à régler": "أرصدة للتسديد",
    "Seulement les retards": "المتأخرات فقط",
    "Tous les soldes non réglés": "كل الأرصدة غير المسددة",
    "Élèves dont une date limite de paiement est dépassée.": "تلاميذ تجاوزوا آخر أجل للدفع.",
    "Élèves qui ont encore un montant à payer, les plus en retard en premier.":
        "تلاميذ لا يزال عليهم مبلغ للدفع، الأكثر تأخرًا أولًا.",
    "reste {montant}": "المتبقي {montant}",
    "dont {montant} en retard": "منها {montant} متأخرة",
    "Relancé le {date}": "تم التذكير بتاريخ {date}",
    "Toutes les familles sont à jour.": "كل الأسر في وضعية سليمة.",
    "Aucun paiement en retard. Si aucune date limite n'est fixée, rien ne peut être en retard : voir Administration › Établissement.":
        "لا توجد دفعات متأخرة. إذا لم يُحدد أي أجل للدفع فلا يمكن احتساب أي تأخير: انظر الإدارة › المؤسسة.",
    "Aucun numéro mobile valide dans le dossier": "لا يوجد رقم هاتف محمول صالح في الملف",
    "Ouvrir WhatsApp avec le message prêt à envoyer": "فتح واتساب مع رسالة جاهزة للإرسال",
    "Téléphone du dossier": "هاتف الملف",
    "Contact d'urgence": "جهة الاتصال في الطوارئ",
    "urgence": "طوارئ",
    "← Précédent": "السابق →",
    "Suivant →": "← التالي",
    "page {page}/{total}": "الصفحة {page}/{total}",
}

# Jours et mois, pour les dates écrites en toutes lettres.
JOURS = ["الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت", "الأحد"]
MOIS = ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس",
        "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"]


# --- Documents officiels ------------------------------------------------------

DOCUMENTS = {
    # Titres et libellés
    "BULLETIN DE NOTES": "كشف الدرجات",
    "CERTIFICAT DE SCOLARITÉ": "شهادة مدرسية",
    "ATTESTATION DE FRÉQUENTATION": "شهادة مواظبة",
    "Reçu de paiement": "وصل دفع",
    "Nom et prénom(s)": "الاسم واللقب",
    "Classe": "القسم",
    "Matricule": "رقم التسجيل",
    "Genre": "الجنس",
    "Féminin": "أنثى",
    "Masculin": "ذكر",
    "Date de naissance": "تاريخ الميلاد",
    "Effectif": "عدد التلاميذ",
    "Matière": "المادة",
    "Moyenne": "المعدل",
    "Coef.": "المعامل",
    "Points": "النقاط",
    "Rang": "الرتبة",
    "Moy. classe": "معدل القسم",
    "Min – Max": "الأدنى – الأعلى",
    "Appréciation": "التقدير",
    "Total": "المجموع",
    "Période": "الفترة",
    "Moyenne générale": "المعدل العام",
    "Moyenne de la classe": "معدل القسم",
    "Plus forte": "أعلى معدل",
    "Plus faible": "أدنى معدل",
    "Mention": "التقدير",
    "Absences": "الغيابات",
    "non justifiée(s)": "دون مبرر",
    "justifiée(s)": "بمبرر",
    "Décision": "القرار",
    "Appréciation du conseil de classe": "ملاحظات مجلس القسم",
    "Année scolaire": "السنة الدراسية",
    "Référence": "المرجع",
    "Date": "التاريخ",
    "Libellé": "البيان",
    "Élève": "التلميذ",
    "Parent(s)": "الولي",
    "Encaissé par": "استلمه",
    "Montant": "المبلغ",
    "N°": "رقم",

    # Périodes
    "1er trimestre": "الفصل الأول",
    "2e trimestre": "الفصل الثاني",
    "3e trimestre": "الفصل الثالث",
    "Année": "الحصيلة السنوية",

    # Mentions et décisions
    "Excellent": "ممتاز",
    "Très bien": "جيد جدًا",
    "Bien": "جيد",
    "Assez bien": "مستحسن",
    "Passable": "مقبول",
    "Insuffisant": "ضعيف",
    "Admis en classe supérieure": "ينتقل إلى القسم الأعلى",
    "Redouble": "يعيد السنة",

    # Titres du signataire
    "Directeur": "المدير",
    "Directrice": "المديرة",
    "Directeur général": "المدير العام",
    "Directrice générale": "المديرة العامة",
    "Fondateur": "المؤسس",
    "Fondatrice": "المؤسسة",
    "Proviseur": "مدير الثانوية",
    "Censeur": "المراقب العام",
    "Principal": "مدير الإعدادية",
    "Comptable": "المحاسب",
    "Secrétaire": "الكاتب",

    # Pays
    "Tchad": "تشاد",
    "TCHAD": "تشاد",

    # Matières courantes
    "Mathématiques": "الرياضيات",
    "Maths": "الرياضيات",
    "Français": "اللغة الفرنسية",
    "Arabe": "اللغة العربية",
    "Anglais": "اللغة الإنجليزية",
    "Histoire-Géographie": "التاريخ والجغرافيا",
    "Histoire": "التاريخ",
    "Géographie": "الجغرافيا",
    "SVT": "علوم الحياة والأرض",
    "Sciences de la vie et de la terre": "علوم الحياة والأرض",
    "Physique-Chimie": "الفيزياء والكيمياء",
    "Sciences physiques": "العلوم الفيزيائية",
    "Sciences": "العلوم",
    "Éducation civique": "التربية المدنية",
    "Éducation civique et morale": "التربية المدنية والأخلاقية",
    "ECM": "التربية المدنية والأخلاقية",
    "EPS": "التربية البدنية",
    "Éducation physique et sportive": "التربية البدنية والرياضية",
    "Éducation islamique": "التربية الإسلامية",
    "Instruction religieuse": "التربية الدينية",
    "Informatique": "الإعلام الآلي",
    "Philosophie": "الفلسفة",
    "Dessin": "الرسم",
    "Musique": "الموسيقى",
    "Lecture": "القراءة",
    "Écriture": "الكتابة",
    "Calcul": "الحساب",
    "Dictée": "الإملاء",
    "Rédaction": "التعبير الكتابي",
    "Grammaire": "القواعد",
    "Conjugaison": "التصريف",
    "Orthographe": "الإملاء",
    "Vocabulaire": "المفردات",
    "Coran": "القرآن الكريم",
}
